### ISSUE TITLE
Publish node-mailjet v2.0.0 on npm

### ISSUE THREAD

**Issue by jspdown** [mailjet/mailjet-apiv3-nodejs#10]
Hi, 

Could you publish the release 2.0.0 on npm? 
FYI the actual version on npm is v1.1.0

**Comment by GuillaumeBadi** [comment]
Hey, by node-mailer, I assume you mean `node-mailjet` ;)

Before publishing it on npm I need to update our official documentation this week

you still can use this method:
``` bash
npm install https://github.com/mailjet/mailjet-apiv3-nodejs/archive/v2.0.0.tar.gz
```

**Comment by jspdown** [comment]
Oh my bad it was `node-mailjet` 😆 

Ok thanks
