### ISSUE TITLE
Button links are disabled when mail is sent from template through API

### ISSUE THREAD

**Issue by NicoBru31** [mailjet/mailjet-apiv3-nodejs#102]
Hi,
I've created a template with Passport and it contains a button which redirects to my website. When I send a test mail through Passport, button is valid and redirection works fine. But when mail is sent from the node API (version 3.3.1), the button is no longer clickable and even the html seems to have changed !
Please see my code below to tell me if I missed something.

`
const Mailjet = require('node-mailjet').connect('xxxx', 'xxxx');

const send = Mailjet.post('send', {version: 'v3.1'});
const options = {
      From: {Name: 'Name', Email: 'foo@bar.fr'},
      ReplyTo: {Name: 'Name', Email: 'foo@bar.fr'},
      TemplateID: 1,
      TemplateErrorDeliver: true,
      TemplateErrorReporting:{Name: 'Name', Email: 'foo@bar.fr'},
      TemplateLanguage: true,
      To: {Name: 'Name', Email: 'bar@foo.fr'},
      Variables: _my variables,_
    };
  send.request({Messages: [options]});
`

Thank you !

**Comment by acestudiooleg** [comment]
Hi, @NicoBru31 are you sure is it related to MailJet SDK? 
Can you provide an example of your Passport code and template?

**Comment by NicoBru31** [comment]
Hi @acestudiooleg , the button has been created with the design tool from the site, I don't know how to export it. I use a variable as button's link, I don't know if this can be the issue.

**Comment by ngarnier** [comment]
@NicoBru31 pretty sure the variable is not properly passed which then breaks the href of the button. Please provide the full HTML and payload so that @acestudiooleg can properly reproduce and debug.

You can download your template as HTML from the template gallery, clicking on the gear icon on the template.

**Comment by NicoBru31** [comment]
See the template of my button below, once again, when I send test mail from Passport it works like a charm. This is only when I send it from node-mailjet that the bug happens

`<a href="{{var:APPLICATION}}" style="display:inline-block;background:#61A3FF;color:#ffffff;font-family:Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px 10px 25px;mso-padding-alt:0px;border-radius:20px;" target="_blank"><span style="background-color:#61A3FF;color:#ffffff;font-family:Verdana;font-size:15px;"><b>Consultez la proposition de votre dénicheur</b></span></a>`

**Comment by acestudiooleg** [comment]
@NicoBru31 I tested your code, I found that variables replaced properly, but the button is not clickable, in my case, it related to Gmail because it received as junk mail and all links removed by default. Also, I tried to send the same email to another address and it works fine

**Comment by NicoBru31** [comment]
@acestudiooleg OMG ! That should be it ! I'll test it with another e-mail client, thank you so much !

**Comment by duplich** [comment]
How is this completed. What is the solution for sending confirmation links to google addresses? How can we avoid our testing links with localhost for example to be marked as spam as rejected?
