### ISSUE TITLE
Outdated transitive agent-base dependency breaks got when node-mailjet is used

### ISSUE THREAD

**Issue by ctavan** [mailjet/mailjet-apiv3-nodejs#103]
`node-mailjet` uses https://github.com/TooTallNate/superagent-proxy which seems to be unmaintained.

Unfortunately `superagent-proxy` depends on https://github.com/TooTallNate/node-proxy-agent which in turn depends on https://github.com/TooTallNate/node-agent-base version 4.x.

This library patches the native node `https.request` method which may cause problems with other libraries like `got`: https://github.com/sindresorhus/got/issues/951#issuecomment-560098292

Apparently this was fixed in `agent-base@5.0.0` (https://github.com/TooTallNate/node-agent-base/pull/36) but since this comes as a transitive dependency of an unmaintained module I don't see an obvious fix.

Are there any plans to get rid of the unmaintained `superagent-proxy` dependency?

**Comment by phoniks** [comment]
I think I'm having an issue related to this.  Everything was going fine until I did an `npm update` and I wound up with the error [referenced here](https://stackoverflow.com/questions/50735345/how-to-authenticate-with-mailjet-without-getting-errors-related-to-node-modules).

**Comment by MariusJ-micro** [comment]
Same issue here. As soon as I import node-mailjet, it breaks requests made by another library based on Got (gitbeaker in that case).

**Comment by Nexum** [comment]
+1

**Comment by Nexum** [comment]
"fix" that seems to work:

`
https.__original_get = https.get;
https.__original_request = https.request;

const Mailjet = require('node-mailjet');

https.get = https.__original_get;
https.request = https.__original_request;
`

**Comment by backbone87** [comment]
this needs to be addressed as it blocks a lot of other popular libs from being upgraded like openid-client

**Comment by andrii-yelis** [comment]
fixed by updating superagent and superagent-proxy
