### ISSUE TITLE
formidable (transitive dependency from superagent) causes problems with webpack

### ISSUE THREAD

**Issue by danielo515** [mailjet/mailjet-apiv3-nodejs#105]
Hello.
One of the transitive dependencies of this project, formidable, has some nasty code that tries to override the require function.
They have already removed that problem, but they didn't released the fix.
Since I read that you want to reduce the number of dependencies, and that superagent is an easy one, maybe you can remove it just now?

Regards

**Comment by acestudiooleg** [comment]
@danielo515 can you describe a problem with webpack? Provide more details, please.

**Comment by danielo515** [comment]
I will be trying to reproduce the issue when I work again on the project where I am using mailjet
