### ISSUE TITLE
App link in email

### ISSUE THREAD

**Issue by Niiitzer** [mailjet/mailjet-apiv3-nodejs#107]
Hi, i tried to add a button in one template using a variable URL. This variable contains a link to be open within an app. For example : <myappname>:// 

The button redirecting to this path is not clickable in my email. Any suggestions on this ?

**Comment by evolkmann** [comment]
Hi @Niiitzer, do you still have the issue?

I was able to make a variable link by using the `{{var:my_variable}}` syntax in the link's url, see example below:
<img width="583" alt="Bildschirmfoto 2020-04-27 um 21 58 45" src="https://user-images.githubusercontent.com/24471188/80415187-77a47e00-88d2-11ea-9121-e0067d1b818b.png">

Make sure that you use the `TemplateLanguage: true` option (this was not clear for me, hence I opened #111). Hope this helps.

**Comment by Niiitzer** [comment]
Yes, thanks for the reply.
Sorry it was not that clear. I can't add a deeplink (myapp://route), which would be opened in the app if i am on my smartphone.

**Comment by evolkmann** [comment]
Okay. Can you show how the variable is configured in your template and what the result looks like in the rendered E-Mail? Maybe we can find the issue then.

**Comment by ngarnier** [comment]
I'm closing this issue as it's not related to the nodejs wrapper. Feel free to reach out to our support if you're still having issues with deeplinks support.
