### ISSUE TITLE
Node wrapper not funcitoning correctly with JSON.stringify().

### ISSUE THREAD

**Issue by hbellala** [mailjet/mailjet-apiv3-nodejs#108]
I am sending an object to a transactional email that I set up but it yields an expression parsing error ## Unknown identifier: var:weeklyOrder.name ## near ## {{ var:weeklyOrder.name ## error. But when I copy and paste the whole JSON.stringify(newWeeklyOrder) text with out changing anything from the console it functions as it should. So I am really confused. 

Here is the API call that doesn't work: const request = mailjet .post("send", {'version': 'v3.1'}) .request({ "Messages":[ { "From": { "Email": "hea@gmail.com", "Name": "Hanth" }, "To": [ { "Email": "hea@gmail.com", "Name": "hea" } ], TemplateID: 12322, TemplateLanguage: true, TemplateErrorReporting: {"Email": "hea@gmail.com"}, "Subject": "Thanks for the order", Variables: { "weeklyOrder": JSON.stringify(newWeeklyOrder) } } ] }) request .then((result) => { console.log(result.body) }) .catch((err) => { console.log(err.statusCode) }) 

Here is the API call that does work: 

const request = mailjet .post("send", {'version': 'v3.1'}) .request({ "Messages":[ { "From": { "Email": "hea@gmail.com", "Name": "hea" }, "To": [ { "Email": "hea@gmail.com", "Name": "hea" } ], TemplateID: 1210173, TemplateLanguage: true, TemplateErrorReporting: {"Email": "hea@gmail.com"}, "Subject": "Thanks for the order", Variables: { "weeklyOrder": {"dietaryRestrictions":["tree NUts"],"_id":"5e3adb5c33aa6d5ec3619d3d","name":"hea hea","email":"hea@gmail.com","phoneNumber":"34","orderee":"hea","paymentType":"Cash App","paymentUsername":"hea","deliveryAddress":{"streetAddress":"2710 hea Ct","addressCont":"","city":"hea City","state":"Georgia","zipcode":"34234","deliveryInstructions":""},"mondayOrders":[],"thursdayOrders":[{"numOfServings":2,"id":"5e398e807969284c08de0720","price":14,"name":"Amazing food","pricePerServing":7,"image":"https://imagebucketfirst.s3.amazonaws.com/Chicken-Fajit-1580830334297.jpg","totalNumOfServings":12}],"subtotal":14,"priceOfDeliveries":3,"total":17,"createdDate":"2020-02-05T15:12:28.573Z","totalNumOfMeals":2,"firstTimeOrder":false} } } ] }) request .then((result) => { console.log(result.body) }) .catch((err) => { console.log(err.statusCode) })

**Comment by acestudiooleg** [comment]
@hbellala  Under the hood, this object is passing into the superagent library and converted into JSON

it is the same as `JSON.stringify( JSON.stringify({ a: {b: 'c'}}) )`

**Comment by andrii-yelis** [comment]
Closing this one, if you still have the issue please open a new one
