### ISSUE TITLE
Nest JS integration

### ISSUE THREAD

**Issue by jmevelson** [mailjet/mailjet-apiv3-nodejs#119]
Hi ,
I'm having trouble integrating the mailJet wrapper into my **NEST JS** application.
I installer the wrapper with NPM like the doc says. But i cannot manage to import the Mailjet module in order to instantiate it so i can connect with my apiKey and secretKey.

I cannot import like the doc advises : `const mailjet = require ('node-mailjet')
    .connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)`

It has to be like :

`import { MailJet} from 'mailjet-sendemail'; `
returns the error `Cannot find module 'mailjet-sendemail' or its corresponding type declarations.ts(2307)` in VS Code

Could you help me clearing that issue plz ?

**Comment by ngarnier** [comment]
Hi @jmevelson, 

Looks like you're mixing two things. Why are you importing he mailjet-sendemail module? It is deprecated as indicated in the readme: https://github.com/mailjet/Mailjet-sendemail. 

If you need the import syntax, just use it on the node-mailjet module: `import mailjet from 'node-mailjet'`.
