### ISSUE TITLE
Module not found: Can't resolve 'dns'

### ISSUE THREAD

**Issue by mschipperheyn** [mailjet/mailjet-apiv3-nodejs#131]
Went through the hello world setup and got this error trying to send an email?
```
error - ./node_modules/pac-resolver/dnsResolve.js:6:0
Module not found: Can't resolve 'dns'
```

**Comment by skylarw19** [comment]
@mschipperheyn I'm getting that error too when I try to connect to mailjet. It works when I connect on a separate js file, but when I try to connect on my function component in next.js/react, I'm getting the same error as you. Were you able to figure out what went wrong?

**Comment by PaulPCIO** [comment]
I'm also getting this error, also using next.js
