### ISSUE TITLE
Upgrade json-bigint to remove High Severity - Prototype Pollution vulnerability

### ISSUE THREAD

**Issue by sasidhar** [mailjet/mailjet-apiv3-nodejs#135]
node-mailjet@3.3.1 has a dependency on `json-bigint@0.2.3` NPM package.

As per Snyk's Test `json-bigint@0.2.3` has a High Severity - Prototype Pollution vulnerability.

Please upgrade `json-bigint` to it's version 1.0.0 or above.

Refer: Snyk's Report at: https://snyk.io/test/npm/node-mailjet/3.3.1

**Comment by flo-sch** [comment]
This was fixed in [v3.3.3](https://snyk.io/test/npm/node-mailjet/3.3.3)

**Comment by sasidhar** [comment]
As this issue is fixed in v3.3.3, marking this issue as closed.
