### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by lunanigra** [mailjet/mailjet-apiv3-nodejs#14]
Hello, we would like to use Mailjet for our project. So far everything good; but the hoster requires using a proxy server.

Can you add support for a proxy server? E.g. use superagent-proxy instead of superagent?

https://www.npmjs.com/package/superagent-proxy

Thanks, JC

**Comment by GuillaumeBadi** [comment]
Hey @lunanigra !

I guess it would be better for you to fork the repository, and then change the dependency yourself. Superagent-proxy would not fit any project, and this library has to remain generic

Guillaume

**Comment by lunanigra** [comment]
Hi @GuillaumeBadi,

Ok, we will try a fork. However I think proxy support is a feature you should add in future.

Regards, JC

**Comment by arnaudbreton** [comment]
Thanks @lunanigra for reporting this. We'll see how we could integrate this request in a future release. Closing it for now.

**Comment by lunanigra** [comment]
Just to mention... It was quite simple to add proxy support.
First add... superagent-proxy

```javascript
const request = require('superagent')
require('superagent-proxy')(request);
```

Then add the proxy to the request and done :-)

```javascript
MailjetClient.prototype.httpRequest = function (method, url, data, callback) {

  var req = request[method](url)
      .set('user-agent', 'mailjet-api-v3-nodejs/' + this.version)

      .set('Content-type', url.indexOf('text:plain') > -1
                         ? 'text/plain'
                         : 'application/json')

  var proxy = process.env.http_proxy
  if (DEBUG_MODE) {
    console.log('proxy: ' + proxy)
  }
  if (proxy) {
    req.proxy(proxy)
  }
```

As proxy support is a common requirement you should think about adding it...
