### ISSUE TITLE
Is this API client still actively maintained?

### ISSUE THREAD

**Issue by flo-sch** [mailjet/mailjet-apiv3-nodejs#145]
Hello,

I am a developer working on behalf of a client, for which I am considering purchasing a Mailjet account.

However I am a bit hesitant due to the activity state of this package, the last official release on NPM is more than 2 years old, and some of the issues & PR were open in 2018 and are not answered, including this high vulnerability report of the [json-bigint](https://github.com/mailjet/mailjet-apiv3-nodejs/issues/135) dependency.

I know it is not always easy for companies to actively maintain SDK & API clients in all languages, but I just would like to know whether this package is still considered as an official integration, with some work planned on maintaining it?

Thanks in advance for a statement, and good luck 🙏

**Comment by bastienlaval** [comment]
Hello,

I've got the same questions / worries than @flo-sch on this API client.
Thanks in advance for your feedback ;-)

Bastien

**Comment by ottovw** [comment]
just created a ticket with mailjet. hopefully someone replys and fixes these security issues.

Other than that, mailjet api works fine @flo-sch :)

**Comment by flo-sch** [comment]
Yeah I have tried it, simple and working well for me :)

**Comment by flo-sch** [comment]
Also for my current use-case (v3.1, transactional emails only, JSON content-type only, no proxy needed), a direct integration towards Mailjet REST API would be rather trivial to build.

But that means maintenance as well (should they update their API) which is my main reason to use this client in the first place :)

**Comment by etiennebatise** [comment]
> just created a ticket with mailjet. hopefully someone replys and fixes these security issues.

@ottovw I've just created the PR fixing the security issues. TBH, I've not spent time testing this. I'll probably do it if this repo needs help in maintenance but unless the CI is fixed (see #148), I doubt this will be released anytime soon.

**Comment by scroll17** [comment]
Hey @flo-sch @bastienlaval @ottovw @etiennebatise 

Now in the current version `3.3.13` [mailjet-apiv3-nodejs](https://github.com/mailjet/mailjet-apiv3-nodejs) haven't any vulnerabilities and this library already has good support and will continue to develop more fast.

As well dependency bluebird was removed in the version `3.3.12`.

In a future major release, most likely `superagent` and `superagent-proxy` will be removed and replaced with something more modern and more freedom for users. 

It is also planned to add more advanced features for this library, revealing the potential of this library as a SDK. And along with the features, full TypeScript support will be added.
