### ISSUE TITLE
pipelines are failing

### ISSUE THREAD

**Issue by Tobi-mmt** [mailjet/mailjet-apiv3-nodejs#148]
It seems like the pipeline is broken for a long time. All pipelines in all PRs are broken.
The older one needs a rebase but the newer one are also broken because of missing environment variables like here https://travis-ci.org/github/mailjet/mailjet-apiv3-nodejs/builds/765466521 

Even the merged PRs has a broken pipeline https://github.com/mailjet/mailjet-apiv3-nodejs/pulls?q=is%3Apr+is%3Aclosed

**Comment by ai-wintermute** [comment]
Hi @Tobi-mmt, I see that the parent issue is [closed](https://github.com/mailjet/mailjet-apiv3-nodejs/issues/145). Was the problem solved for you?
Please let us know if you have any questions.
This issue will be closed in 48h.
