### ISSUE TITLE
npm audit: netmask npm package high vulnerable to octal input data 

### ISSUE THREAD

**Issue by cksanders** [mailjet/mailjet-apiv3-nodejs#150]
- High :: netmask npm package vulnerable to octal input data
- Package :: netmask  
- Patched in :: >=2.0.1 
- Dependency of :: node-mailjet  
- Path  :: node-mailjet > superagent-proxy > proxy-agent >  pac-proxy-agent > pac-resolver > netmask 
- More info :: https://npmjs.com/advisories/1658

**Comment by Tobi-mmt** [comment]
There are some open PRs which resolves this like #149  #147 and #137 .
But the mailjet people do no merge the stuff

**Comment by cksanders** [comment]
thanks @Tobi-mmt - we have raised a support ticket directly with them, hopefully they'll get one of these reviewed/merged.

**Comment by Tommy-42** [comment]
hello there, sorry for the delay, I've raised the issue internally, we'll get back to you soon !
Thanks for raising this issue to us !

**Comment by bfischetti** [comment]
Any news on this? @Tommy-42

**Comment by scarney81** [comment]
@Tommy-42 - Any updates? It's been nearly 3 weeks since the last response.

**Comment by Tobi-mmt** [comment]
@Tommy-42 The speed for high security issues is really disappointing 🙁
Like written before the community opened 4 PRs to fix this problem, first one was opened before the security issue raised: https://github.com/mailjet/mailjet-apiv3-nodejs/pull/137 the other ones only days later; #147 #149 #152

Please take some minutes and merge one of them.

(Of course I have no idea why it takes so long and there are perhaps good reasons. But as a customer of your service I think with this slow development speed and intransparent communication – even within security issues – we really have to think about to remove mailjet as email provider in our client applications. We can not offer software where high security issues last so long)

**Comment by Tommy-42** [comment]
Sorry guys @Tobi-mmt @scarney81 @bfischetti , After I saw the issue and reported the trouble, I went on vacation and couldn't follow up on this.

I am back and catching up today with that issue and will let you know, we really care about security and make it our priority, something must have caught up with the team to avoid dealing with this one !

**Comment by Fryuni** [comment]
Any news on this? The last release is 3 years old, it's been more than a month since this security issue was reported, and now there is another one. We still have not received any update on this.

We reviewed our use case to ensure it does not touch the vulnerable code, but it is completely unmanageable to do this for a library. As @Tobi-mmt said, this brings some serious reason to switch mail providers since there are multiple PRs fixing the problem from the community.

**Comment by ludwigward** [comment]
@johnwook we will do the same, it is in the backlog already. I have not looked at the details of SES yet but do you know if that is the best alternative or are there other ones out there?

**Comment by johnwook** [comment]
@ludwigward Of course SES is not a drop-in replacement of mailjet. Mailjet do something very nice :( But in my case I think we can build it for my own.

BTW, I've heard that [mxroute](https://mxroute.com/) is quite a good (I've never used them ;))

**Comment by luisvsm** [comment]
@Tommy-42 can you check out #135 while you're at it too please?

**Comment by damien-monni** [comment]
Hi @Tommy-42 any news?

**Comment by Kitafe** [comment]
Hi @Tommy-42 , Would be nice if there was a fix.

**Comment by luisvsm** [comment]
Is there a security team we could loop in?

**Comment by Tommy-42** [comment]
Hello guys, 

sorry for keeping you waiting, I have good news, it should be taken care of tomorrow 

cc @damien-monni @Kitafe @luisvsm @cksanders @Tobi-mmt @bfischetti @scarney81 @Fryuni @johnwook

**Comment by mblog** [comment]
There was an update to 3.3.3 today, but the critical part wasn't fixed.

**Comment by Tommy-42** [comment]
@mblog there was a push for a 3.3.4 right after, I believe it is now fixed ? 

cc https://github.com/mailjet/mailjet-apiv3-nodejs/commit/efeb45fc7e8874ef17d7fad90f601927bf98e5ba

**Comment by flo-sch** [comment]
@Tommy-42 the vulnerability is indeed fixed, thanks for your help :)

https://snyk.io/advisor/npm-package/node-mailjet

**Comment by olexandr-mazepa** [comment]
> @Tommy-42 the vulnerability is indeed fixed, thanks for your help :)
> 
> https://snyk.io/test/npm/node-mailjet/3.3.4
It looks like the issue is fixed so I close this.
