### ISSUE TITLE
v3.1 isn't working?

### ISSUE THREAD

**Issue by Emiliano-Bucci** [mailjet/mailjet-apiv3-nodejs#151]
Hi! For some reason i've recently start to face a strange issue; using version 3.1, as indicated in the docs, I've start to get this issue `at least FromEmail or Sender must be provided`. Looking in the logs, and in the node implementation of the library, I see that the version is picked from the `./config.json` file which is v3. The strange thing is that I've started to get this issue recently (and changing the version from 3 to 3.1 manually solve this issue). Anyone is facing a similar issue?

Thanks!

**Comment by scroll17** [comment]
Hey @potatozerg @Emiliano-Bucci 
You can provide more information about problem such as code and other something useful information ?

**Comment by scroll17** [comment]
This issue will be closed
