### ISSUE TITLE
ErrorMessage "At least FromEmail or Sender must be provided" v3.1, start showing this error 2 days ago

### ISSUE THREAD

**Issue by potatozerg** [mailjet/mailjet-apiv3-nodejs#157]
It was working perfectly.

**Comment by longhornleads** [comment]
Is there a fix for this yet? This is a breaking change for sure. This just started appearing.

**Comment by potatozerg** [comment]
@longhornleads go to config, v3 -----> v3.1

**Comment by TheRealPaulyglot** [comment]
is there any fix to this error?

**Comment by potatozerg** [comment]
> is there any fix to this error?

Not yet, have to fix it manually.

**Comment by scroll17** [comment]
Hey @potatozerg @longhornleads @PaulESanchezC 
You can provide more information about problem such as code and other something useful information ?

**Comment by potatozerg** [comment]
I think it's fixed already

**Comment by PaulESanchezC** [comment]
If I remember correctly it was because I was trying to use the json format to send the email, and I had to use the fluent apis

**Comment by scroll17** [comment]
Well, i will be close this issue ?
