### ISSUE TITLE
Node SDK: Options variable is not a valid object

### ISSUE THREAD

**Issue by DharmarajX24** [mailjet/mailjet-apiv3-nodejs#158]
**throw new Error('warning, your options variable is not a valid object.')**

The error points to this:
```
import nodeMailjet from "node-mailjet"
const mailjet = nodeMailjet.connect(process.env.MAILJET_API_KEY, process.env.MAILJET_API_SECRET)
```
The env keys are correct and I am not even passing options object. It's a typescript project. 
It does run on `Ubuntu (Node 12)` but this error occurs on `Windows (Node 14)`.

SDK Version: `v3.3.1`

**Comment by flo-sch** [comment]
Which versions of `@types/node-mailjet` do you use?

I also use TypeScript and have no issue, using the same pattern as you (default export + process.env keys)

```bash
➜ yarn list --pattern mailjet
├─ @types/node-mailjet@3.3.4
└─ node-mailjet@3.3.1
```

**Comment by DharmarajX24** [comment]
@flo-sch same versions.

**Comment by DharmarajX24** [comment]
@flo-sch it's hard to reproduce the issue. Later I had switched back to Ubuntu.  I don't have the full stack trace but here's snap.
![image](https://user-images.githubusercontent.com/63334359/118965102-eb09a980-b985-11eb-8870-21928745366f.png)
Then I went through the source code and found that [here](https://github.com/mailjet/mailjet-apiv3-nodejs/blob/06932fea6aa323a7095b5b33608cfeb7a531aa9c/mailjet-client.js#L228). 

Apparently, clearing cache and a clean install of node modules helped. Though I can confirm the versions were same.

**Comment by scroll17** [comment]
Hey @DharmarajX24 

Yes, this problem pops up from the place where you indicated:
```javascript
MailjetClient.prototype.setConfig = function (options) {
  const config = require('./config')
  if (typeof options === 'object' && options != null && options.length != 0) {
    if (options.url) config.url = options.url
    if (options.version) config.version = options.version
    if (options.perform_api_call) config.perform_api_call = options.perform_api_call
  } else if (options != null) {
    throw new Error('warning, your options variable is not a valid object.')
  }

  return config
}
```

And if you don't call method `setConfig` on MailjetClient instance that mean that error was occur due to `const config = require('./config')` and this problem was solved in PR [fix: problem with wrong using require for load config.json file](https://github.com/mailjet/mailjet-apiv3-nodejs/pull/193).

In actual version `3.3.10` of this library this error must be not exist.

**Comment by scroll17** [comment]
This issue will be closed
