### ISSUE TITLE
Older Node compatibility

### ISSUE THREAD

**Issue by oscar-b** [mailjet/mailjet-apiv3-nodejs#16]
Running in an environment I can't control, which is on an older Node version (AFAIK it's 0.12).

The `=>` syntax doesn't work, at least. Which is the minimum required version of Node?

**Comment by GuillaumeBadi** [comment]
The versions tested by travis can be found here : https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/.travis.yml (the latest stable release of Node is 4.4.7)

**Comment by oscar-b** [comment]
So that's the minimum required version? I know 0.12 is ancient and hope the environment will be upgraded soon :/

**Comment by GuillaumeBadi** [comment]
Solved! ;)

Please `npm install --save node-mailjet` again :)

Guillaume

**Comment by oscar-b** [comment]
Very nice, thank you! Will verify and test later tonight and let you know.

**Comment by oscar-b** [comment]
Verified :)

Thanks again for the quick fix!
