### ISSUE TITLE
Mailjet err.statusCode 401

### ISSUE THREAD

**Issue by Mustafobek** [mailjet/mailjet-apiv3-nodejs#163]
Hello! Just trying to send some emails with given example code in mail https://app.mailjet.com/auth/get_started/developer but getting error 401! how can we solve that issue?

**Comment by flo-sch** [comment]
401 is an authentication error, there must be a problem with the way you configure API keys somehow

Hard to say which one without the context though (which API version, which methods do you use etc.)
If you can provide a code snippet showing how you integrate the API, it would be helpful ;)

**Comment by scroll17** [comment]
Hey @Mustafobek 
On the page [Status Codes & Errors](https://dev.mailjet.com/email/reference/overview/errors/) you can see response status codes and descriptions for them.

And at the page [Send your first email](https://app.mailjet.com/auth/get_started/developer) provided fully valid code, i'm duplicate his below: 
```javascript
const mailjet = require ('node-mailjet')
.connect('****************************1234', '****************************abcd')
const request = mailjet
.post("send", {'version': 'v3.1'})
.request({
  "Messages":[
    {
      "From": {
        "Email": "pilot@mailjet.com",
        "Name": "Pilot"
      },
      "To": [
        {
          "Email": "passenger@mailjet.com",
          "Name": "Passenger"
        }
      ],
      "Subject": "Greetings from Mailjet.",
      "TextPart": "My first Mailjet email",
      "HTMLPart": "<h3>Dear passenger 1, welcome to <a href='https://www.mailjet.com/'>Mailjet</a>!</h3><br />May the delivery force be with you!",
      "CustomID": "AppGettingStartedTest"
    }
  ]
})

request
  .then((result) => {
    console.log(result.body)
  })
  .catch((err) => {
    console.log(err.statusCode)
  })

```

**Comment by scroll17** [comment]
This issue will be closed
