### ISSUE TITLE
Mailjet API_KEY is required even with API KEY

### ISSUE THREAD

**Issue by leonllrmc** [mailjet/mailjet-apiv3-nodejs#164]
I've got the error Mailjet API_KEY is required 
my Code: 
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const mailjet = require ('node-mailjet')
    .connect(process.env.USER, process.env.PASSWORD)
const app = express();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(bodyParser.raw());

app.post('/sendMail',async (req, res) => {
    mailjet
    .post("send", {'version': 'v3.1'})
    .request({
        "Messages":[{
            "From": {
                "Email": "leonllrcraft@gmail.com",
                "Name": "thesportclinic server"
            },
            "To": [{
                "Email": req.body.to,
                "Name": "Alexis"
            }],
            "Subject": "nouveau demande de rendez-vous",
            "TextPart": "",
            "HTMLPart": `${req.body.body}`
        }]
    }).then((result) => {
    console.log(result.body)
    res.status(200);
  })
  .catch((err) => {
    console.log(err.statusCode)
  })

    
})

app.listen(process.env.PORT)
console.clear()//just for Repl.it don't log express server
```

**Comment by ricky11** [comment]
Why are you passing in user and password, I think you need to pass in your public and private key instead of user and password?

**Comment by leonllrmc** [comment]
It's just var name but it's api keys like say in exemple

**Comment by simonlayfield** [comment]
I'm also experiencing this issue. @leonllrmc did you manage to find a way around it by any chance?

**Comment by leonllrmc** [comment]
> Je rencontre également ce problème. @leonllrmc avez-vous réussi à trouver un moyen de le contourner par hasard ?

No 😥

**Comment by scroll17** [comment]
@leonllrmc @simonlayfield 
I'm tested this problem and the error is not reproduced.

The error you are getting is generated in file `mailjet-client.js` on line `191`: 
```javascript
...
  function basicConnectStrategy(apiKey, apiSecret, options) {
    if (!apiKey) {
      throw new Error('Mailjet API_KEY is required');
    }
    if (!apiSecret) {
      throw new Error('Mailjet API_SECRET is required');
    }
....    
```

The code check value `apiKey`  for not empty value (`0, "", null, undefined, NaN` in Boolean have value `false`) so you need to check that values `process.env.USER` and `process.env.PASSWORD` aren't empty.

Please, check you passed values and if error repeat with not empty values provide more information: NodeJS version, OS, environment

**Comment by scroll17** [comment]
This issue will be closed
