### ISSUE TITLE
Which api to create a new contact with properties and add to list

### ISSUE THREAD

**Issue by ricky11** [mailjet/mailjet-apiv3-nodejs#165]
Do i need to make multiple calls to the api if i want to do the steps below

1) Create a new contact
2) Assign properties to the contact
3) Add contact to a list.

Since i have only 1 list and do want all my contacts to be assigned to a list, what is the API to do all the above 3 in one call?

**Comment by scroll17** [comment]
Hey @ricky11 
Yes, for these steps you need make multiple calls to the API. 

MailJet support bulk operations but they intended for other things.
- Send bulk messages via API `v3.1` - [Send in bulk](https://dev.mailjet.com/email/guides/send-api-V3/#send-in-bulk)
- [Manage the subscription status of a single contact to multiple contact lists](https://dev.mailjet.com/email/guides/contact-management/#manage-the-subscription-status-of-an-existing-contact)
- [Manage the subscription status of multiple contacts to a single contact list](https://dev.mailjet.com/email/guides/contact-management/#manage-multiple-contacts-in-a-list)
- [Manage the subscription status of multiple contacts to multiple contact lists](https://dev.mailjet.com/email/guides/contact-management/#manage-multiple-contacts-across-multiple-lists)

For more detailed information you can visit [DEV GUIDE](https://dev.mailjet.com/email/guides/contact-management/) page.

In your case you need do steps below:

1. Create a new contract - [Contract API](https://dev.mailjet.com/email/reference/contacts/contact/)
```javascript
const mailjet = require ('node-mailjet')
	.connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)
	
const request = mailjet
	.post("contact", {'version': 'v3'})
	.request({
           "IsExcludedFromCampaigns": "true",
           "Name": "New Contact",
           "Email": "passenger@mailjet.com"
        })
    
request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})
```

2. Manage contact properties

[Contract properties API](https://dev.mailjet.com/email/reference/contacts/contact-properties).
On the first step you need to define custom data properties for Contract: 
```javascript
const request = mailjet
	.post("contactmetadata", {'version': 'v3'})
	.request({
          "Datatype": "str",
          "Name": "first_name",
          "NameSpace": "static"
        })
    
request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})
```

[Update Contact metadata API](https://dev.mailjet.com/email/reference/contacts/contact-properties/#v3_put_contactdata_contact_ID)
And then on the second step you can add, edit or update the data saved for a specific contact:
```javascript
const request = mailjet
	.put("contactdata", {'version': 'v3'})
	.id($contact_ID)
	.request({
          "Data":[
            {
              "Name": "first_name",
              "Value": "John"
             }
           ]
         })
    
request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})
```

3. Manage a contact list 

[Contact list API](https://dev.mailjet.com/email/reference/contacts/contact-list/)
On the first step you need to create a contact list:
```javascript
const request = mailjet
	.post("contactslist", {'version': 'v3'})
	.request({
          "Name": "my_contactslist"
        })
    
request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})
``` 

[List recipient API](https://dev.mailjet.com/email/reference/contacts/subscriptions#v3_post_listrecipient)
And then on the second step you can add a contact to a contact list:
```javascript
const request = mailjet
	.post("listrecipient", {'version': 'v3'})
	.request({
           "IsUnsubscribed": "true",
          "ContactID": "987654321",
          "ContactAlt": "passenger@mailjet.com",
          "ListID": "123456",
          "ListAlt": "abcdef123"
        })
    
request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})
```

**Comment by scroll17** [comment]
This issue will be closed

**Comment by ozgrozer** [comment]
It's a shame that we can't make this in one request.

**Comment by HKandulla** [comment]
As far as I understand the documentation, it is possible to create (or update) a contact including properties and assign the contact to an existing list in one call. Using:
`POST /contactslist/{list_ID or list_address}/managecontact`

[v3_post_contactslist_list_ID_managecontact](https://dev.mailjet.com/email/reference/contacts/subscriptions/#v3_post_contactslist_list_ID_managecontact
)

Of course, the contactlist and the contact-properties must exists.

**Comment by adam2211** [comment]
You can create a contact with properties and add it to a list all in one call using this end point

https://api.mailjet.com/v3/REST/contactslist/{{listID}}/managecontact

Example JSON:

{
    "Email": "example22@example.com",
    "Name": "MrSmith",
    "Action": "addnoforce",
    "Properties": {
        "phone": 6969699696,
        "refcode": "valueN"
    }
}
