### ISSUE TITLE
Send email to a segment with variables

### ISSUE THREAD

**Issue by KhalidScrypt** [mailjet/mailjet-apiv3-nodejs#167]
Hello,

I am trying to schedule periodic emails to be sent to segments (location based) with a list of requests in their location.
So I would need to add variables for this. 
Is there a way to send email using the API to a segment? I found how to send it to a contact list but it will tedious to create a list for each location.
I tried to use https://api.mailjet.com/v3/REST/campaigndraft too but then I'm not sure I can use variables in the campaign).

Thank you.

**Comment by ricky11** [comment]
Why not use automated emails for this?

**Comment by ricky11** [comment]
I dont work for mailjet, but if you need periodic emails as you mentioned, you can use custom properties on the users profile to segment users. then create an automated template to send a series of emails based on that segment,

I think you will need to create one automated email per segment if you use the automated way.

Another ways is to use the API as you mentioned, but then you wont need to rely on the segments, just query your database and filter out eh emails that need to be send that day. Then you need to run that function daily on your backend system.

I use postmark for my transactional emails, but you have to code everything yourself. Mailjet automated templates may help you which require no coding.

**Comment by KhalidScrypt** [comment]
Yes I'm already using the automated emails for onboarding and other "straightforward" emails communication.
The fact I would like to include data from the app (requests in the app that are not contact properties) is making the automation feature not enough :) 
I also thought about just fetching the emails and sending individual emails through API but then that will multiply the API calls by how many emails I have. 
I can also create a contact list for each location... which I might do if there is no solution from the Mailjet team, considering we won't have more than 10 location at the beginning (but might grow later) :)

**Comment by ricky11** [comment]
Perhaps automated templating is not feature-rich enough for you, but it can do a lot if you play around with it, it is quite rigid however, once you set it , you cant change it which is a pity.

Why cant you send batch emails with one function call?  You would not multiple the api calls per email, you can send batches of emails that match your filter and then use the corresponding template id.

I am not sure how your backend works, but i assume you are using a database to store the locations, and i would rather not rely on mailjet data unless you are sure they are up to date and rather use your database to filter and batch email from there.

good luck.. mailjet support takes about 2-3 weeks to get a reply!

**Comment by KhalidScrypt** [comment]
True, just saw I can send batch mails with one API call! Might consider this :) 
Yes I'm keeping data synchronized between my database and Mailjet: Name, location, language... are updated when user updates them). 
Using segments with send email API call would be great but if not possible, I think I have 2 or 3 workarounds with a bit more work :)

**Comment by scroll17** [comment]
Hey @KhalidScrypt 

Yes, MailJet don't provide feature a custom variables in _campaign_ but i find other way how you can use for you case.

 Below i provide all steps for you case which includes code examples, links on the guides and references: 
 
 Code begin: 
 ```javascript
 const Mailjet = require('./mailjet-client')
 
 const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

...
 ```
 
 1. At the first step you need create a contact then a contacts list and add the contact to contacts list: 
 
 More information in the [Contact Management dev guide page](https://dev.mailjet.com/email/guides/contact-management/).
 
 ```javascript
 ;(async () => {
    // 1. create contact
    const contactName = 'New Contact'
    const contactEmail = 'passenger@mailjet.com'

    const { body: createdContactData } = await mailjet
        .post("contact", {'version': 'v3'})
        .request({
            IsExcludedFromCampaigns: "true",
            Name: contactName,
            Email: contactEmail
        })

    const contactId = createdContactData.Data[0].ID;

    // 2. create contacts list
    const contactsListName = 'my_contactslist'

    const { body: createdContactsListData } = await mailjet
        .post("contactslist", {'version': 'v3'})
        .request({
            Name: contactsListName
        })

    const contactsListId = createdContactsListData.Data[0].ID;

    // 3. add a contact to a contacts list
    const response = await mailjet
        .post("listrecipient", {'version': 'v3'})
        .request({
            IsUnsubscribed: true,
            ContactID: contactId,
            ListID: contactsListId,
        })
})()
 ```
 
 2. At the second step you need add custom properties to the contact
 
This step was resolved two your problem: variables for segmentation by user location and putting the requests information (title, description...) in variables.

More information how manage [Contact properties](https://dev.mailjet.com/email/guides/contact-management#manage-contact-properties).
[Dev reference by Contract properties](https://dev.mailjet.com/email/reference/contacts/contact-properties/)

In the begin you need define properties in contact entity: 
```javascript
;(async () => {
    // 1. create contact properties 
    const response = await mailjet
        .post("contactmetadata", {'version': 'v3'})
        .request({
            "Datatype": "str",
            "Name": "location",
            "NameSpace": "static"
        })
})()
```

And then you need add some data to this contact property: 
```javascript
;(async () => {
    const contactId = 23523
    
    // 2. add some data to contact property
    const response = await mailjet
        .put("contactdata", {'version': 'v3'})
        .id(contactId)
        .request({
            "Data":[
                {
                    "Name": "location",
                    "Value": "New York"
                }
            ]
        })
})()
```

This steps above needs for create segmentation.
And by this steps you can define and add other contact properties such as `title` and `description`.

3. At the third step you need create a segmentation, template and campaign. 

"I can also create a contact list for each location" - no, you don't need create a contact list for each location but you need many segments for each location and you need a single contact list should be contained all contacts for their you want send emails and each contact must be have property `location`.

From begin you need create segmentation. 
[The dev guide by segmentation](https://dev.mailjet.com/email/guides/segmentation/), at this page you can see how create segmentation and how use different expressions on it.

At code example below i show how create a segmentation for users from New York: 
```javascript
;(async () => {
    // 1. create segmentation
    const response = await mailjet
        .post("contactfilter", {'version': 'v3'})
        .request({
            Description: "Will send only to contacts at New York place.",
            Expression: "(place=\"New York\")",
            Name: "Customers at New York"
        })
})()
```
You need create the segmentation for each user place. 

The next step is creating a template:
- [Dev guide by template API](https://dev.mailjet.com/email/guides/template-api/)
- [How use template language](https://dev.mailjet.com/email/guides/send-api-v31#use-templating-language)
- [How use personalization in templates](https://dev.mailjet.com/email/guides/send-api-v31#personalization)
- [Dev reference by MailJet template language](https://dev.mailjet.com/email/template-language/reference/)
- [API reference by Template API](https://dev.mailjet.com/email/reference/templates)
- [Dev guide by MailJet Passport](https://dev.mailjet.com/email/template-language/passport/)

In the templates you can use a contact properties: 
```
<html>
  <body>
    {% if segment:nameSegment %}
    <h1>Recipient {{mj:contact.email}} matches segment nameSegment</h1>
    {% endif %}
  </body>
</html>
```

And in the end you need create a campaign with `SegmentationID` and `TemplateID`: 
```javascript
;(async () => {
    // 1. create campaign draft
    const response = await mailjet
        .post("campaigndraft")
        .request({
            Locale: "en_US",
            Sender: "Pilot",
            SenderEmail: emailFrom,
            Subject: "For all from New York",
            ContactsListID: 13239,
            SegmentationID: 2294,
            TemplateID: 3885745,
            Title: "Test campaign"
        })
})()
```

Useful information by campaigns: 
- [Dev guide by send campaigns using `/campaigndraft`](https://dev.mailjet.com/email/guides/send-campaign-drafts/)
- [Dev reference by campaign drafts](https://dev.mailjet.com/email/reference/campaigns/drafts/)
- [Dev reference by sent campaigns](https://dev.mailjet.com/email/reference/campaigns/sent-campaigns/)

4. At the last step you need schedule and run you campaign:

[Dev reference for `/campaigndraft/{draft_ID}/schedule`](https://dev.mailjet.com/email/reference/campaigns/drafts#v3_post_campaigndraft_draft_ID_schedule) 

```javascript
;(async () => {
    // 1. schedule campaign 
    const response = await mailjet
        .post("campaigndraft", {'version': 'v3'})
        .id(3885745)
        .action("schedule")
        .request({
            "Date": "2018-01-01T00:00:00"
        })
})()
```

**Comment by scroll17** [comment]
This issue will be closed
