### ISSUE TITLE
Can't resolve ./config in node-mailjet building with Angular Universal

### ISSUE THREAD

**Issue by denisyilmaz** [mailjet/mailjet-apiv3-nodejs#172]
related to the issue #121 I'm not able to build the Server-side bundle for Angular when importing `node-mailjet`.
It fails with `Module not found: Error: Can't resolve './config' in '/opt/app/node_modules/node-mailjet'`

--- 

While investigating i found a solution which fixes the issue:

https://github.com/mailjet/mailjet-apiv3-nodejs/blob/efeb45fc7e8874ef17d7fad90f601927bf98e5ba/mailjet-client.js#L222

Angular does not support imports of JSON files without `.json` extension as the TypeScript module resolver is currently not capable of doing so. As Angular moved away from Webpack there is no way to get around this limitation.

Simple fix is to change Line 222  in mailjet.client.js to:
```js
  const config = require('./config.json')
```
and adding this to the `tsconfig.json` of Angular:
```json
{
  "compilerOptions": {
    "resolveJsonModule": true
  }
}
```

More information (via https://stackoverflow.com/a/67559739):

- https://www.typescriptlang.org/docs/handbook/module-resolution.html
- https://github.com/microsoft/TypeScript/issues/24357

**Comment by denisyilmaz** [comment]
anyone?

**Comment by HarmNullix** [comment]
A whole bunch of code unusable because one config file is poorly included json file..
Here is an option of how I fixed it:
https://github.com/mailjet/mailjet-apiv3-nodejs/pull/138#issuecomment-1095087102

**Comment by scroll17** [comment]
Hey @denisyilmaz 
Thank you for such a detailed description of the problem.

I created pull request with fixed this problem and in the near future it will be merged and added to the master branch.
