### ISSUE TITLE
Upgrade pac-resolver to remove vulnerability

### ISSUE THREAD

**Issue by MixalisVak** [mailjet/mailjet-apiv3-nodejs#175]
Hello,
There is a vulnerability coming from node-mailjet package.

- High :: Code Injection

- Package :: pac-resolver

- Patched in :: >=5.0.0

- Dependency of :: node-mailjet

- Path :: node-mailjet > superagent-proxy > proxy-agent >pac-proxy-agent > pac-resolver

- More info ::  https://npmjs.com/advisories/1784

If it is possible to upgrade the pac-resolver to version 5.0.0 or later

Thanks,
Mixalis

**Comment by OG84** [comment]
but be careful this will break webpack builds! 
pac-resolver -> degenerator -> vm2
vm2 is dynamically loading contextify.js from the filesystem (not requiring) which then is not present when bundled by webpack, esbuild etc.
So this change could lead to some production build of apps which are using node-mailjet

**Comment by sushantdhiman** [comment]
After waiting from some time, I have finally written an update version of this library https://github.com/sushantdhiman/mailjet-js. Available on npm as `mailjet-js`, updated dependencies, removed `bluebird` and bundled typescript typing.

**Comment by eric-burel** [comment]
Hi guys, this seems like a relatively severe security issue, any plan to solve this from Mailjet?

**Comment by EloyID** [comment]
We have the same issue, would like to get it solved soon :)

**Comment by alexfriesen** [comment]
So I just uninstalled this package and use the REST API directly.

```
axios.post("send", { messages }, {
    baseURL: `https://${API_URL}/v3.1/`,
    auth:{
        username: API_KEY,
        password: API_SECRET
    },
});
```
This way I got rid of all the bloat that comes with it

**Comment by qqilihq** [comment]
Reported on **28 Sep** and no fix or official feedback. We'll definitely need to re-evaluate if Mailjet is the right solution for us going forward.

**Comment by MikeRippon** [comment]
Following suit and dropping this library due to lack of support. Highly disappointing for a service we pay for.

**Comment by perusopersonale** [comment]
PR #182 should fix this, it's merged in master but no new release. I've open a new issue.

**Comment by danielluca** [comment]
We will also use this approach now 👌

> So I just uninstalled this package and use the REST API directly.
> 
> ```
> axios.post("send", { messages }, {
>     baseURL: `https://${API_URL}/v3.1/`,
>     auth:{
>         username: API_KEY,
>         password: API_SECRET
>     },
> });
> ```
> 
> This way I got rid of all the bloat that comes with it

**Comment by scroll17** [comment]
Hello
Now in the version `3.3.10` [mailjet-apiv3-nodejs](https://github.com/mailjet/mailjet-apiv3-nodejs) haven't any vulnerabilities.

**Comment by scroll17** [comment]
This issue will be closed
