### ISSUE TITLE
Wrongly send error-responses and no ErrorIdentifier documentation (other than for the send API) | NodeJS

### ISSUE THREAD

**Issue by Jonathan-Hofmann** [mailjet/mailjet-apiv3-nodejs#181]
Hey MailJet-Dev-Team,

I am currently very frustrated with of how your API documentation is structured and also how the api endpoints (other then `send`) return errors.

As of today I wanted to start working on a better error-handling logic in my backend with MailJet.
But fortunately it is not as easy as one could think it would be...

At this point I've tried for at least 4h to figure out how to catch errors correctly and check them if they are `fatal` or not. 
From my point of view, it is currently not possible to detect errors and check them if they are `fatal` or not.  

# IMO 1st problem: API error documentation
When I try to research all possible error-codes and `ErrorIdentifiers` for the api endpoints ( `contacts` and `lists` ) there are no results. 
Even when I am using Google search the algorithm only finds 'Status Codes & Errors' for the entire API.

> That a status code `400` / `401` means that an error appeared is clear to me but my question is `what kind of error appeared and how to identify them?`.

# IMO 2nd problem: API responses
As I have tried to somehow categorize the error response I found out that it is (at least with my version of mailJet installed) not possible.
Every time I get the error JSON response the field `ErrorIdentifier` is always `undefined` which makes it hard to categorize the error. 

Even weirder is that the Identifier (at least I think it is the missing identifier) is being send within the `ErrorMessage`.

f.ex.
```shell
ErrorMessage: 'MJ18 A Contact resource with value "XXXXXX@XXX.com" for Email already exists.',
ErrorIdentifier: undefined,
statusCode: 400,
```

Also the `body` object of the response has the same error:
```shell
body: {
      ErrorInfo: '',
      ErrorMessage: 'MJ18 A Contact resource with value "XXXXXX@XXX.com" for Email already exists.',
      StatusCode: 400
    },
```

### Our Future with MailJet
if this malfunction will not be fixed in the near future we as a company are sorry to say that we are not willing to pay at least 20€ a moth for an API that is not working as intended.

I hope you guys can fix this relatively small issue in the near future so we can continue using mailJet!
Greetings from Hamburg, Germany
J.

#### Using:
node-mailjet Version 3.3.4
nodeJS Version 16.13.1

**Comment by scroll17** [comment]
Hey @Jonathan-Hofmann 

You can visit page [Status Codes & Errors](https://dev.mailjet.com/email/reference/overview/errors/) when written:
```
- Codes in the 2xx range indicate that the request was processed successfully.
- Codes in the 4xx range indicate that there was an error with the request (e.g. unauthorized access, a required parameter is missing etc.).
- Codes in the 5xx range indicate that there is an issue with Mailjet's servers. Those are quite rare.
```

**Comment by scroll17** [comment]
This issue will be closed
