### ISSUE TITLE
Question: will this work directly on ReactJS?

### ISSUE THREAD

**Issue by justinbalaguer** [mailjet/mailjet-apiv3-nodejs#192]

**Comment by scroll17** [comment]
Hey @justinbalaguer 
I not sure is it so but some people use this lib with Angular and webpack.
As you know ReactJS from the box provide the react-cli wich using webpack.

As well you can test this by yourself.

**Comment by justinbalaguer** [comment]
Test out and didnt work. Also found a comment by one of the creators/maintainers that this should be used with server side and not any other frontend framework. Ill close this later when I'm back and mention that comment.

**Comment by scroll17** [comment]
Yes, this library designed to work only with the server. 
But dependencies of this library let work with the browser too. 

You can provide for me errors log, if exist, and i can help for you.

As well you can create issue with request possibility to work in the browser.
May be if creators approve this we will be add this opportunity.

**Comment by scroll17** [comment]
This issue will be closed

**Comment by scroll17** [comment]
Hey @justinbalaguer 
I want to inform you that Mailjet team decide to add possible work on both the server and client sides.
In the next major releases, this opportunity will be added.

**Comment by scroll17** [comment]
Hey @justinbalaguer 
Now released `v4` version - [npm](https://www.npmjs.com/package/node-mailjet/v/4.0.0) where we added TypeScript support and added both server and browser side.
You can find examples based on `ReactJS` in the folder `examples/react`.

**Comment by justinbalaguer** [comment]
sweet. btw all is good for the subscription api. thank you so much.
