### ISSUE TITLE
Object not found on a 7 digit ID

### ISSUE THREAD

**Issue by justinbalaguer** [mailjet/mailjet-apiv3-nodejs#201]
`{ "ErrorInfo" : "", "ErrorMessage" : "Object not found", "StatusCode" : 404 }`

```
curl -s \
	-X POST \
	--user "<api-key-here>:<api-secret-here>" \
	https://api.mailjet.com/v3/REST/contactslist/<id-here-eg-1234567>/managecontact \
	-H 'Content-Type: application/json' \
	-d '{
      "Name":"John Smith",
      "Properties":"object",
      "Action":"addnoforce",
      "Email":"passenger@mailjet.com"
	}'
```

however when I tested this on my newly created account and using the id e.g `.id('12345')` if perfectly works.
p.s: also tried using the mailjet address - didn't work

**Comment by justinbalaguer** [comment]
@scroll17 doing this, its just an empty array for my other account im using (old account), however using my new account shows an array in data.

```javascript
const request = mailjet
   .get("contactslist", { version: 'v3' })
   .request()
   .then((result) => {
       console.dir(result.body, { depth: 10 })
   })
```

**Comment by scroll17** [comment]
Hello @justinbalaguer 

---

You can use a web version for control **Contacts**, **Contact properties**, **Contact lists** and etc. by this links: 
- [Contact lists](https://app.mailjet.com/contacts)
- [All Contacts](https://app.mailjet.com/contacts/subscribers/contact_list)
- [Contact properties](https://app.mailjet.com/contacts/lists/properties)

And you should explore the `Mailjet` web version where you can find different features which you can use via `browser` or directly via `API`, fox example: 
- [Templates builder](https://app.mailjet.com/templates/marketing)
- [Campaigns management](https://app.mailjet.com/campaigns)
- [Contacts management](https://app.mailjet.com/contacts)

---

Helpful materials about `Sub-account`: 
- [What are sub-accounts and how does it help me?](https://documentation.mailjet.com/hc/en-us/articles/360042561854-What-are-sub-accounts-and-how-does-it-help-me-)
- [How to create a sub-account (or additional API Key)?](https://documentation.mailjet.com/hc/en-us/articles/360042561974-How-to-create-a-sub-account-or-additional-API-Key-)

And in [this article](Simplified Collaboration Using Sub-accounts With Mailjet) from `Mailjet` blog said that: 
> That’s where sub-accounts come in handy. They let you manage multiple different accounts (or API keys) under one master account. If you’re an agency, you can separate clients. If you send both marketing and transactional emails, you can separate lists and templates.

> Work together more easily with your colleagues or your clients by giving them access to your sub-accounts, while keeping an eye on their campaigns.

---

In general, you can [contact our Support Team](https://app.mailjet.com/support/ticket/open) for more detailed information and troubleshooting.
