### ISSUE TITLE
Update API contact documentation to show contact has to created before adding to a contact list

### ISSUE THREAD

**Issue by davidklemme** [mailjet/mailjet-apiv3-nodejs#208]
I think its easy to assume you can use the endpoint to create a contact and add it to a list.

However, 

you'll need to check if the contact exists already, if not, create it and than and that to an existing contact list.
It would be very helpful if the documentation could show that.

(Even greater would be if the endpoint handles all the cases..)

Thanks.

Cheers, 
David

**Comment by scroll17** [comment]
Hey @davidklemme 
I'm working for update documentation now, can you please share with me a link for the place where you want to see this mention about "you'll need to check if the contact exists already, if not, create it and than and that to an existing contact list." ?

**Comment by texiontech** [comment]
I think it should be one step to add the contact to contact list without create contact and then add it to contact list, because when you call this action it's mean you need to add this contact to the contact list which is I don't care does it exist or not if it exist just skip if not create the new one.

**Comment by scroll17** [comment]
Hey @texiontech 

Thanks for your explanation!
I agree with you, and I think it will be friendly behavior, but unfortunately, I can't make any changes on the **Mailjet** server-side, only on the library side that sends requests to this server.

But you can **open a ticket** in the **Mailjet Support Center** by this [link](https://app.mailjet.com/support) and ask to implement this improvement.

**Comment by scroll17** [comment]
Hey @davidklemme 

I tried to find a documentation part in this [repo](https://github.com/mailjet/api-documentation) for adding a notice block about the required action "create contact before adding it to contact list" but I don't found it and I don't have access to another repo with documentation for **Mailjet**. 

For this reason, I can suggest a solution for you and it's **open a ticket** in the **Mailjet Support Center** by this [link](https://app.mailjet.com/support) and ask to implement this improvement.

**Comment by ai-wintermute** [comment]
Hi @davidklemme, thank you for the improvement suggestion. 
Unfortunately, as it was mentioned above, we can't make any changes neither to Mailjet server itself nor to the documentation repo, only to this SDK library. 
Please contact the Mailjet Support Center by the [link](https://app.mailjet.com/support) to address this.
Sorry for the inconvenience and thank you for the cooperation!
This issue will be closed in 48h.
