### ISSUE TITLE
Status success but MessageHref results in 404 and no email sent/received

### ISSUE THREAD

**Issue by CanRau** [mailjet/mailjet-apiv3-nodejs#213]
Sending an email I get `result?.response?.status === 200` and as you can see below `Status` in the body says `success` as well, though no email has been actually sent, according to dashboard and also I don't receive any.

```
{
  From: { Name: 'Name', Email: 'mail@example.com' },
  To: [ { Name: 'Can', Email: 'recipient@gmail.com' } ],
  TemplateID: 4082179,
  Variables: {
    LINK: 'https://example.com/en/path',
    USER_DISPLAY_NAME: 'Can'
  },
  TemplateLanguage: true
}
[Object: null prototype] {
  Messages: [
    [Object: null prototype] {
      Status: 'success',
      CustomID: '',
      To: [
        [Object: null prototype] {
          Email: 'recipient@gmail.com',
          MessageUUID: 'c7b0201f-29ab-4f01-b42a-8d437201397d',
          MessageID: '576460765503091475',
          MessageHref: 'https://api.mailjet.com/v3/REST/message/576460765503091475'
        }
      ],
      Cc: [],
      Bcc: []
    }
  ]
}
```

But going to `https://api.mailjet.com/v3/REST/message/576460765503091475` entering my API key I get

```
{ "ErrorInfo" : "", "ErrorMessage" : "Object not found", "StatusCode" : 404 }
```

I've sent a test mail from Passport, so the template seems to work fine

This is my code

```ts
export const sendMail = (Messages: Email.SendParamsMessage[]) =>
  mailjet.post("send", { version: "v3.1" }).request({
    Messages,
  });

sendMail([{ From, To: [to], TemplateID, Variables, TemplateLanguage: true }]);
```
with this data

```
{
  From: { Name: 'Name', Email: 'mail@example.com' },
  To: [ { Name: 'Can', Email: 'recipient@gmail.com' } ],
  TemplateID: 4082179,
  Variables: {
    LINK: 'https://example.com/en/path',
    USER_DISPLAY_NAME: 'Can'
  },
  TemplateLanguage: true
}
```

**Comment by CanRau** [comment]
Just tried to use `HTMLPart` and `TextPart` instead of TemplateID, though with the same result

**Comment by scroll17** [comment]
Hello @CanRau 

We already had a similar issue with the same problem - [Email send but not recived](https://github.com/mailjet/mailjet-apiv3-nodejs/issues/207). 
I tried to reproduce that issue but didn't receive the same problem. 

I think it can be a bug on the **Mailjet** server-side because I can't reproduce it on my local host with my account and because it's the second issue with the same problem.
Please follow this [link](https://app.mailjet.com/support) where you can **open a ticket** in the **Mailjet Support Center**.

**Comment by scroll17** [comment]
Hey
I'm going to close this issue tomorrow, do you have any questions yet?

**Comment by CanRau** [comment]
At the moment no, thank you, I just opened a ticket.

**Comment by fxdave** [comment]
I'm sorry for necrobumping, but I have the same issue and I couldn't find this ticket in the Mailjet Support Center.
@CanRau Do you remember this case?

**Comment by CanRau** [comment]
@fxdave not completely, also not using mailjet anymore tho I just dug up the support reply

> The issue is that the "From" address you are using mail@example.com is not verified as a valid sending address under the API key the message is attempted to be sent from

Think I might've mixed up stuff in the dashboard and not validated the email/domain in the right account (top right when you click on the username menu you can switch accounts)

Hope this helps

**Comment by CanRau** [comment]
Where did you switch to?
We're using SES now, more low level but I like it a lot 🤓

**Comment by fxdave** [comment]
AWS is good although they should fix their typing in the client lib. Having undefined everywhere is a bit overwhelming. However, I used it like 1 or 2 years ago so it might be irrelevant.
Either way, my client uses CampaignMonitor also so that was my choice. :)

**Comment by ruaanvds** [comment]
Posting here for posterity: **if you're on the free tier, you're limited to 200 emails per day.** 

![Image](https://github.com/user-attachments/assets/3ba7c3e0-3b03-4ad6-975d-b3473d0290af)

No errors, no warnings - 200 responses all the way. I just wasted half a day on debugging this.
