### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by MaxLmqr** [mailjet/mailjet-apiv3-nodejs#217]
Hello,

I am having an issue when trying to use the library with typescript in NestJS. I have the following code :
```
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import Mailjet, { SendEmailV3_1 } from 'node-mailjet';

@Injectable()
export class MailjetService {
  private mailjet: Mailjet;

  constructor(private readonly configService: ConfigService) {
    this.mailjet = new Mailjet({
      apiKey: this.configService.get('MJ_APIKEY_PUBLIC'),
      apiSecret: this.configService.get('MJ_APIKEY_PRIVATE'),
    });
  }

  async sendForgottenPasswordMail(token: string, recipientMail: string) {
    const data: SendEmailV3_1.IBody = {
      Messages: [
        {
          From: {
            Email: 'some@email.com',
            Name: 'SomeName',
          },
          To: [{ Email: recipientMail }],
          TemplateID: SOME_TEMPLATE_ID,
        },
      ],
    };

    const res = await this.mailjet
      .post('send', { version: 'v3.1' })
      .request<SendEmailV3_1.IResponse>(data);

    const { Status } = res.body.Messages[0];
  }
}
```

Typescript says : 
```
Type 'IResponse' does not satisfy the constraint 'TRequestData'.
Type 'IResponse' is not assignable to type 'TUnknownRec'.
Index signature for type 'string' is missing in type 'IResponse'.ts(2344)
```

I can't see any difference between my current code here and the documentation example, so any help is welcome. I think I'm probably missing something here.

`package.json` version : 5.1.1

Bests,
Max

**Comment by qqilihq** [comment]
We're having this very issue. Any comments on that?

**Comment by Jendorski** [comment]
I resolved like so and I hope you find this useful.

     
     const Mailjet = require('node-mailjet')//Yes, I used require in typescript like this

     const mailJetApiKey = this.configService.get(config.MAILJET_API_KEY)
        const mailJetSecretKey = this.configService.get(config.MAILJET_SECRET_KEY)

        const construc: IClientParams = {
            apiKey: mailJetApiKey,
            apiSecret: mailJetSecretKey,
        }

        this.mailjet = new Mailjet(construc);
        
        let body: TRequestData = { /** Your body comes in here*/ }
        
        //Notice I did not use a type for the response and in the request
        const data =  await client
          .post('send', { version: 'v3.1' })
          .request(body);
        
        return Promise.resolve(data.body)

**Comment by fehnomenal** [comment]
What about this? So your data is still strictly typed:

```ts
    const data: SendEmailV3_1.IBody = {
      Messages: [
        {
          From: { Email: 'abc@email.email' },
          To: [{ Email: 'abc@email.email' }],
          HTMLPart: '...',
        },
      ],
    };

    await mailjet.post('send', { version: '3.1' }).request({ ...data });
```

**Comment by MichaelBitard** [comment]
That's probably because `request` expect a `TBody extends TRequestData` and nothing extends TRequestData.

From the example on getContact: 
```typescript
const result = await mailjet
    .get('contact', { version: 'v3' })
    .request<Contact.TGetContactResponse>({}, queryData);
```
this cannot compile

**Comment by woodinteractive** [comment]
I'm having an issue just trying to get it instantiated.
```TS
export class MailjetService {
	private _transporter: nodemailer.Transporter
	private mailjet: Mailjet
	constructor(private readonly configService: ConfigService) {
		this.mailjet = new Mailjet({
			apiKey: process.env.MJ_APIKEY_PUBLIC,
			apiSecret: process.env.MJ_APIKEY_PRIVATE
		})
...
```

Error output says:
`TypeError: node_mailjet_1.default is not a constructor`

Am I missing something?

**Comment by dlariosuniandes** [comment]
> I'm having an issue just trying to get it instantiated.
> 
> ```ts
> export class MailjetService {
> 	private _transporter: nodemailer.Transporter
> 	private mailjet: Mailjet
> 	constructor(private readonly configService: ConfigService) {
> 		this.mailjet = new Mailjet({
> 			apiKey: process.env.MJ_APIKEY_PUBLIC,
> 			apiSecret: process.env.MJ_APIKEY_PRIVATE
> 		})
> ...
> ```
> 
> Error output says: `TypeError: node_mailjet_1.default is not a constructor`
> 
> Am I missing something?

I'm having the same issue did you just found how to solve it ?

**Comment by dlariosuniandes** [comment]
> I'm having an issue just trying to get it instantiated.
> 
> ```ts
> export class MailjetService {
> 	private _transporter: nodemailer.Transporter
> 	private mailjet: Mailjet
> 	constructor(private readonly configService: ConfigService) {
> 		this.mailjet = new Mailjet({
> 			apiKey: process.env.MJ_APIKEY_PUBLIC,
> 			apiSecret: process.env.MJ_APIKEY_PRIVATE
> 		})
> ...
> ```
> 
> Error output says: `TypeError: node_mailjet_1.default is not a constructor`
> 
> Am I missing something?

Never mind I think there must be something wrong with their node package config and it doesn't allow us to import the module with the ES6 default syntax. If you want a quick fix/workaround just use require instead.

**Comment by Codesleuth** [comment]
I think that the following code is fundamentally flawed:

```ts
const result = await mailjet
  .post('send', { version: 'v3.1' })
  .request({ ...data });

// result is ILibraryResponse<TRequestData>
```

The type of `result` should not represent `TRequestData` - that's a request shape, not a response shape.
You actually want it to be `ILibraryResponse<SendEmailV3_1.IResponse>` but it isn't compatible.

A workaround is to use a type assertion:

```ts
function isSendResponse(r: unknown): r is ILibraryResponse<SendEmailV3_1.IResponse> {
  return r != null
    && typeof r === 'object'
    && 'Messages' in r
    && Array.isArray(r as { Messages: unknown });
}

const result = await mailjet
  .post('send', { version: 'v3.1' })
  .request({ ...data });

if (isSendResponse(result)) {
  const { Status } = result.body.Messages[0];
  // ...
} else {
  // probably never hit, but you just don't know
  throw new Error('Unexpected response body');
}
```

Arguably, this is more reliable than if the type system worked today. At least in this code, there's runtime checking of the response to give you some level of confidence that the API response is what you expect. Feel free to extend `isSendResponse` with further checks for what you need (maybe a json schema check?)

**Comment by AdhamMoussa** [comment]
@dlariosuniandes  @woodinteractive 
adding `"esModuleInterop": true` to your tsconfig.json file will fix that issue

**Comment by ai-wintermute** [comment]
Hi @MaxLmqr did you try suggestions from above? Did it work for you?
Please let us know if you have any questions, otherwise the issue will be closed in 48h.

**Comment by qqilihq** [comment]
None of the suggestions above fix the original issue - the typings distributed with the module (and/or the corresponding documentation) are fundamentally broken and need to be fixed.

**Comment by MaxLmqr** [comment]
As mentioned by @qqilihq, the original issue is still present, and I'm currently using the library without any of the provided types.

**Comment by ai-wintermute** [comment]
Got it, thank you for the quick response! Just wanted to double-check before starting investigating the issue.

**Comment by ai-wintermute** [comment]
Hello @MaxLmqr, TypeScript fix is available in the new major [release](https://github.com/mailjet/mailjet-apiv3-nodejs/releases/tag/v6.0.0). Types naming was changed so please refer the [Readme](https://github.com/mailjet/mailjet-apiv3-nodejs#typescript) for more details.

**Comment by qqilihq** [comment]
I just gave this a try. The TS examples in the readme compile, BUT everything is typed to `any` now. No type safety at all.

```typescript
  const mailjet = new Mailjet({ apiKey, apiSecret });

  const queryData: Contact.GetContactQueryParams = {
    IsExcludedFromCampaigns: false,
    Campaign: 2234234,
  };

  const result = await mailjet
    .get('contact', { version: 'v3' })
    .request<Contact.GetContactResponse>({}, queryData);

  // const result: LibraryResponse<Body>
  // no auto-completion on result, no type safety for result
```

I am doing something wrong or misunderstanding the usage?

**Comment by ai-wintermute** [comment]
Response type will be `LibraryResponse<Contact.GetContactResponse>`. 
`LibraryResponse<Body>` is a generic so you need to specify what exact entity you're using. Then, you'll get all of the Contact properties:
```
    const result: LibraryResponse<Contact.GetContactResponse>  = await mailjet
        .get('contact', { version: 'v3' })
        .request<Contact.GetContactResponse>({}, queryData);

    const contactArr = result.body.Data;
        contactArr.map(contactItem => contactItem.Name);
```
Please let us know if something is unclear.

**Comment by qqilihq** [comment]
But the response type is already passed as type argument with the request method:

```typescript
.request<Contact.GetContactResponse>({}, queryData);
```

Above snippet is exactly as given in the project’s readme. It does not mention at all, that the `result` needs to be explicitly typed like so:

```type
const result: LibraryResponse<Contact.GetContactResponse>
```

I appreciate your efforts trying to get the types proper, but having to repeat this twice feels rather clunky and not very TS-like.

**Comment by ai-wintermute** [comment]
Sure, you don't need to put the type twice, just remove it in the `request` part. So it should be:
```
const result: LibraryResponse<Contact.GetContactResponse>  = await mailjet
        .get('contact', { version: 'v3' })
        .request({}, queryData);
```
Sorry, missed that during the copy-pasting. Will update the readme to avoid the ambiguity.

**Comment by qqilihq** [comment]
> Will update the readme to avoid the ambiguity.

Thank you! 🙂

**Comment by MaxLmqr** [comment]
Thank you, I will look into it.

**Comment by rujorgensen** [comment]
Regarding the "TypeError: node_mailjet_1.default is not a constructor" that some people are having: I removed `"module": "commonjs"` from `compilerOptions` in my tsconfig.json. Luckily that was an option for me, but it might not be for everybody.
