### ISSUE TITLE
TypeScript: Globals still required in Messages array

### ISSUE THREAD

**Issue by swantzter** [mailjet/mailjet-apiv3-nodejs#218]
Hi,

The following TypeScript code (simplifed to the bare minimum) will yield the TypeScript Error `error TS2741: Property 'From' is missing in type '{ To: { Email: string; }[]; }' but required in type 'IMessage<TUnknownRec, TUnknownRec>'.`, but since it's defined in Globals it should not error and From should be optional in the Messages object.

```ts
const data: SendEmailV3_1.IBody = {
  Globals: {
    From: {
      Email: 'example@example.com',
      Name: 'example'
    }
  },
  Messages: [{
    To: [{
      Email: 'example@example.com',
    }]
  }]
}
```

**Comment by ai-wintermute** [comment]
Hello @swantzter, can you please check the [latest](https://github.com/mailjet/mailjet-apiv3-nodejs/releases/tag/v6.0.0) (6.0.0) version of the package? `Globals` field is not required, there are only following required fields:
```
const data: SendEmailV3_1.Body = {
        Messages: [{
            From: {
                Email: 'example@example.com'
            },
            To: [{
                Email: 'example@example.com',
            }]
        }]
    }
```

**Comment by swantzter** [comment]
@ai-wintermute the issue persists in v6.0.0.
The thing I'm having problems with is that, as you say, `Messages.From` is required in the TS type. But the Mailjet API does not require `Messages.From` if `Globals.From` is present.

The ideal solution would be that `Messages.From` is not required if `Globals.From` is present, and it is required if `Globals.From` is not present

So I expect the following examples to **pass** the type checking:
```ts
const data: SendEmailV3_1.Body = {
  Globals: {
    From: {
      Email: 'example@example.com',
      Name: 'example'
    }
  },
  Messages: [{
    To: [{
      Email: 'example@example.com',
    }]
  }]
}
```

```ts
const data: SendEmailV3_1.Body = {
  Messages: [{
    From: {
      Email: 'example@example.com',
      Name: 'example'
    },
    To: [{
      Email: 'example@example.com',
    }]
  }]
}
```

And I expect these to **fail** the type checking
```ts
const data: SendEmailV3_1.Body = {
  Globals: {
  },
  Messages: [{
    To: [{
      Email: 'example@example.com',
    }]
  }]
}
```

```ts
const data: SendEmailV3_1.Body = {
  Messages: [{
    To: [{
      Email: 'example@example.com',
    }]
  }]
}
```

**Comment by ai-wintermute** [comment]
Oh, I see, thank you for explanation. I'll be working on the fix then.

**Comment by ai-wintermute** [comment]
Hi @swantzter the [new 6.0.1 version](https://github.com/mailjet/mailjet-apiv3-nodejs/releases/tag/v6.0.1) with the fix was published. Please  check and let me know if you have any issues.
