### ISSUE TITLE
Unable to send emails using a template

### ISSUE THREAD

**Issue by vihuvac** [mailjet/mailjet-apiv3-nodejs#220]
Following the documentation to send an email using a template does not work, I am trying to send an email using the API v3.1, e.g: [Guide to use a Template](https://dev.mailjet.com/email/guides/send-api-v31/#use-a-template).

I even tried to instantiate the `apiConnect` as in [this documentation](https://github.com/mailjet/mailjet-apiv3-nodejs#make-your-first-call) but non of the previous guides worked.

I inspected the request and the mails apparently were sent without errors, but in the mail report they appear as blocked.
When I tested the template, the email was sent successfully, the template is currently active.
I got two emails verified to act as senders.

The following snippet is being executed within an _async_ function, the response return a _200_ status code with some more details without errors but the mails appear as blocked in the report:

```javascript
const request = await mailjet.post('send', { version: 'v3.1' }).request({
  Messages: [
    {
      From: {
        Email: '<SENDER_EMAIL>',
        Name: '<SENDER_NAME>',
      },
      To: [
        {
          Email: '<DESTINATION_EMAIL>',
          Name: '<DESTINATION_NAME>',
        },
      ],
      TemplateID: 12345678, // This is not the real templateID.
      TemplateLanguage: true,
      Subject: '<EMAIL_SUBJECT>',
    },
  ],
});
```

Can someone help me please?

**Comment by ai-wintermute** [comment]
Hi @vihuvac, are you still experiencing this issue? Just wanted to double-check before starting the investigation.

**Comment by ai-wintermute** [comment]
@vihuvac I'm going to close this issue in 48h. Please let me know if you still need an assistance.
