### ISSUE TITLE
Unable to view templates in template gallery

### ISSUE THREAD

**Issue by azpery** [mailjet/mailjet-apiv3-nodejs#221]
Since today we are unable to access the templates we create through API / nodejs client. 

`request = await mailjet.post("template", { version: "v3" }).request({
        Author: "Tënk",
        Name: name,
        Purposes: ["marketing"],
        EditMode: 4,
        OwnerType: "user",
        Categories: ["newsletter"],
        IsStarred: false,
        IsTextPartGenerationEnabled: true,
        Locale: "fr_FR",
      });`

This returns ids, as it was created but nothing shows in our templates : https://app.mailjet.com/templates/marketing

We changed nothing on our implementation. We are experiencing anomalies since this morning. 

Thanks

**Comment by ai-wintermute** [comment]
Hi @azpery, are you still experiencing this issue? What version of the library do you use?

**Comment by ai-wintermute** [comment]
@azpery I'm going to close this issue in 48h. Please let me know if you still need an assistance.
