### ISSUE TITLE
SMS fails to send for certain numbers

### ISSUE THREAD

**Issue by driannaude** [mailjet/mailjet-apiv3-nodejs#223]
Mailjet version: `5.1.1`
Node version: `16.15.1`

When making requests to send an SMS to some numbers, `node-mailjet` throws the following error:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
```

Additionally, a `GET` to `https://api.mailjet.com/v4/sms` returns the following status and description:

```json
{
  "ID": "REDACTED",
  "From": "REDACTED",
  "To": "REDACTED",
  "Status": {
    "Code": 13,
    "Name": "rejected_system_error",
    "Description": "Message rejected due to an unexpected system error"
  },
  "Cost": {
    "Value": 0.0714,
    "Currency": "EUR"
  },
  "CreationTS": 1663373792,
  "SmsCount": 1
}
```

This particular exception only seems to happen for a specific carrier in New Zealand. With or without leading `0`. All other numbers we've tested work fine and send as expected. 

Phone number context:
Country: `New Zealand (+64)`
Carrier: `Vodafone (number starts with 021 or 21)`

**Comment by ai-wintermute** [comment]
Hi @driannaude do you still facing this issue?

**Comment by driannaude** [comment]
Hey @ai-wintermute , I probably should have come back and given this update a while back. On further investigation it appears that this issue was with Skinny (not Vodafone) - this particular set of users had ported their Vodafone numbers to Skinny. 

Unfortunately, we never found a solution and ended up using Twilio instead. Unsure if this issue still persists today, it's been a few months since we attempted to use Mailjet's SMS API.

**Comment by ai-wintermute** [comment]
Got it, thank you for the quick response! I'm closing this issue then. Please let us know if you need anything else from our side.
