### ISSUE TITLE
NodeJS returns an "Object: null prototype"

### ISSUE THREAD

**Issue by ozapienCeneval** [mailjet/mailjet-apiv3-nodejs#225]
Using node-mailjet version 5.1.1 returns an Object: null prototype on response.body for a successfully send email action:

##response.body
```
response =>  [Object: null prototype] {
  Messages: [
    [Object: null prototype] {
      Status: 'success',
      CustomID: '',
      To: [Array],
      Cc: [],
      Bcc: []
    }
  ]
}
```
send a CURL or direct POST using POSTMAN return correct information:

Example of POSTMAN received data:
```
{
    "Messages": [
        {
            "Status": "success",
            "CustomID": "",
            "To": [
                {
                    "Email": "user@example.com",
                    "MessageUUID": "d52904a5-aa9f-493c-ab48-f393bc778bf9",
                    "MessageID": 1234567890123456789,
                    "MessageHref": "https://api.mailjet.com/v3/REST/message/1234567890123456789"
                }
            ],
            "Cc": [],
            "Bcc": []
        }
    ]
}
```

**Comment by andresfccy** [comment]
Anything new for this one?

**Comment by ai-wintermute** [comment]
Hi @ozapienCeneval this is not a bug but an expected Node behaviour when you're trying to use `console.log` for object which has null prototype. 
If you want to get rid of it, you can either use `JSON.parse(JSON.stringify(response.body))` or `Object.assign({}, response.body)`. Also, if you're using Express, you can use a middleware: `app.use(bodyParser.urlencoded({extended: true}))`.
