### ISSUE TITLE
Create contact and add it to a list

### ISSUE THREAD

**Issue by josylad** [mailjet/mailjet-apiv3-nodejs#228]
Hello, 
I am working on a project and I need to add new contacts to a list. 
Basically, I need to: 

- Create a new contact
- Assign properties to the contact
- Add contact to a list. 

**Something like:** 
```
data = {
	      'IsUnsubscribed': "true",
	      'ContactAlt': email,
	      'ListID': "029209202",
	      'Email': email,
	      'Firstname':firstname ,
	      'Lastname': lastname,
	      'Country': country,
	      'phone': phone,
	      }
		result = mailjet.contact.create(data=data)
		print(result.status_code)
		print(result.json())
```

**Which Endpoint can do this?  I will appreciate a python code sample.**

**Comment by ai-wintermute** [comment]
Hello @josylad, try this:
```
from mailjet_rest import Client
import os
api_key = os.environ['MJ_APIKEY_PUBLIC']
api_secret = os.environ['MJ_APIKEY_PRIVATE']
mailjet = Client(auth=(api_key, api_secret), version='v3')
data = {
  [put your data here]
}
result = mailjet.contactslist.create(data=data)
print result.status_code
print result.json()
```
Endpoint used for this is `POST https://api.mailjet.com/v3/REST/contactslist`
Please let me know if you need anything else from our side. 
This issue will be closed in 48h.
