### ISSUE TITLE
Error while loading in Cloudflare Workers

### ISSUE THREAD

**Issue by nileshtrivedi** [mailjet/mailjet-apiv3-nodejs#230]
I get the following error with `require('node-mailjet')` within a Cloudflare Worker:

```
notes: [
      {
        text: 'Uncaught ReferenceError: define is not defined\n' +
          '  at index.js:19:5 in node_modules/node-mailjet/mailjet.web.js\n' +
          '  at index.js:6:50 in __require\n' +
          '  at index.js:2129:15\n' +
          ' [code: 10021]'
      }
    ],
```

As you can see, it's loading `mailjet.web.js` and not `mailjet.node.js`. This is probably because, as [Cloudflare Docs](https://workers.cloudflare.com/works) say:

> Many packages that require Node dependencies, such as fs or net/http, aren't supported in Workers because Workers isn't Node—it's [built on V8](https://developers.cloudflare.com/workers/learning/how-workers-works)

It would be great to be able to use this library in Cloudflare Workers environment.

**Comment by nileshtrivedi** [comment]
This happens even when I use the `--node-compat` flag for [Node compatibility](https://developers.cloudflare.com/workers/wrangler/configuration/#node-compatibility) with my wrangler command.

**Comment by eweren** [comment]
No updates here?

**Comment by haydencleary** [comment]
Having the same issue here 🙋‍♂️ @nileshtrivedi did you find a work-around or a different service ? In my current situation this makes Mailjet unusable for me.

**Comment by nileshtrivedi** [comment]
@haydencleary I ended up keeping MailJet but switched to Netlify Functions instead of Cloudflare which is a very unique environment.

**Comment by ai-wintermute** [comment]
Hi @nileshtrivedi sorry for the long response. Unfortunately, we are not going to support Cloudflare workers in the nearest versions. But you are always welcome to suggest your features/improvements by creating a pull request to the library.
