### ISSUE TITLE
global leaks in mailjet-client.js

### ISSUE THREAD

**Issue by timaschew** [mailjet/mailjet-apiv3-nodejs#24]
Just pass it through eslint and you get lot of errors because of **no-undef**, which means in this case that variables are not declared with a var, let, or const, so they are globale

These variables are affected:

`config`
`url`
`api_version`
`secured`
`perform_api_call`

**Comment by Zhivko-Mailjet** [comment]
Hi @timaschew 

Thanks for spotting and reporting the problem. We will investigate the root cause on our end and will get back to you when we have some updates.
