### ISSUE TITLE
Custom unsubscribe link

### ISSUE THREAD

**Issue by luminous8** [mailjet/mailjet-apiv3-nodejs#240]
Hi,

I need to generate a personalized unsubscribe email for transactional emails.

I'm doing this but it doesn't work
`
const recipientsList = users.map((user) => {
      return {
        Email: user.email,
        Variables: {
          unsubscribeLink: 'https://domain.com/unsubscribe?email=${user.email}&id=${user.uniqueId}',
        },
      };
    });
`

And in my mjml file
`{{ unsubscribeLink }}`

How can i achieve this?

Thanks

**Comment by ai-wintermute** [comment]
@luminous8 I'm going to close this ticket as it's not library-related. If you need any help on this you can contact Customer Assistant from your Mailjet account.
