### ISSUE TITLE
Mailjet not send the template language part in the message

### ISSUE THREAD

**Issue by sayinmehmet47** [mailjet/mailjet-apiv3-nodejs#243]
I am using mailjet to send notification to user if they upload a file. So I created a template like that

[![enter image description here][1]][1]
[![enter image description here][2]][2]

But when i got the message it only send the title and first description part, it does not send the template language part.
[![enter image description here][3]][3]

I dont know if I send the request wrongly. That is how I implemented the request 

```js
 async sendNotificationMail() {
    try {
      await this.mailClient.sendMail({
        to: 'mehmet.sayin@steiner.ch',
        template: '4714581',
        AdvanceErrorHandling: true,
        variables: {
          userName: 'Mehmet',
          projectName: 'Test Project',
          senderName: 'Mehmet',
          senderEmail: 'sayinmehmet47@gmail.ch',
        },
      });
    } catch (error) {
      this.logger.error(error);
    }
  }

```

am I need to activate sth to show also template language part? I also tried it with **        TemplateLanguage: true,
** but does not show that part. 

  [1]: https://i.stack.imgur.com/G33hC.png
  [2]: https://i.stack.imgur.com/5E3mc.png
  [3]: https://i.stack.imgur.com/GYEcM.png

**Comment by ai-wintermute** [comment]
Hi @sayinmehmet47 it should be a `'Mj-TemplateLanguage': true` property not a `TemplateLanguage`.
Here's a detailed [documentation](https://dev.mailjet.com/email/guides/send-api-V3/#use-template-language) on that, please take a look.

**Comment by sayinmehmet47** [comment]
@ai-wintermute  thanks for your answer.I dont know if is is the case. I also defined it in the header and tried the **Mj-TemplateLanguage=true**. but did not worked for me. HERE  how is I defined it 
```js 
  async sendMail(mailDto: MailDto) {
    const sendMailOptions: ISendMailOptions = {
      to: mailDto.to,
      from: mailDto.from ?? this.defaultMailFrom,
      text: mailDto.text,
      subject: mailDto.subject,
      html: mailDto.html,
      headers: {
        'X-MJ-TemplateID': mailDto.template || '',
        'X-Mj-TemplateLanguage': '1',
        'X-MJ-Vars': JSON.stringify(mailDto.variables || {}),
        'X-MJ-TemplateErrorReporting': '1',
      },
    };

    this.logger.debug('sendMail', JSON.stringify(sendMailOptions));
    try {
      await this.mailerService.sendMail(sendMailOptions);
    } catch (error) {
      this.logger.error('Sending Mail failed', error);
    }
  }

```
