### ISSUE TITLE
cant use .connect or .apiconnect 

### ISSUE THREAD

**Issue by xXTim97Xx** [mailjet/mailjet-apiv3-nodejs#255]
`const Mailjet = require('node-mailjet');`
`const mailjet = Mailjet.apiConnect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE);`

I always receive errors like "**Mailjet.apiConnect is not a function**" or "**Mailjet.connect is not a function**"

**Comment by ai-wintermute** [comment]
Hi, @xXTim97Xx can you share a bit more context on the environment you're using? Node version, library version etc.

**Comment by xXTim97Xx** [comment]
Node Version: 15.8.0
React: 17.0.1
node-mailjet: 6.0.3

**Comment by xXTim97Xx** [comment]
![image](https://github.com/mailjet/mailjet-apiv3-nodejs/assets/47519975/c33b81c0-0661-4cb5-bf6c-1771607a5598)

You can also check my IntelliSense that it really is not shown here

**Comment by ai-wintermute** [comment]
So you're trying to use `require` in the client's code? You can't do this as it's part of the node CommonJS module system.
Can you use import instead? As described here: https://github.com/mailjet/mailjet-apiv3-nodejs#send-email-example

**Comment by xXTim97Xx** [comment]
Yes, thanks a lot. This seems to work that way.
But how do I use the proxy hack for testing?

I'm always receiving a CORS Error now
