### ISSUE TITLE
Axios update

### ISSUE THREAD

**Issue by tiny-dancer** [mailjet/mailjet-apiv3-nodejs#261]
Hey,

We're getting flagged for node-mailjet vulnerability via: https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459.

I didn't see any where else in the README to submit this issue, please handle accordingly.

Thanks

**Comment by FElliger** [comment]
FYI, there's a PR for this here: https://github.com/mailjet/mailjet-apiv3-nodejs/pull/263 (not mine)

**Comment by ai-wintermute** [comment]
Here's a new release with updated Axios version: https://github.com/mailjet/mailjet-apiv3-nodejs/releases/tag/v6.0.5
