### ISSUE TITLE
Unit testing mailjet mocking

### ISSUE THREAD

**Issue by joliejuke-orga** [mailjet/mailjet-apiv3-nodejs#27]
Hi,

I created a module that wrap your nodeJS module but I would like to unit test the HTTP call and mock the responses.

Is there a place where I can find the full API reference with the response - or JSON mock ressources?
I didn't find response reference here: https://dev.mailjet.com/email-api/v3/contact/

Best.

**Comment by Zhivko-Mailjet** [comment]
Hi @joliejuke-orga 

Apologies for the delayed response. Unfortunately, we do not have a dedicated reference for the response only. You can use our guides as a model where you can find most of the responses we return -> https://dev.mailjet.com/guides/#about-the-mailjet-restful-api

Should you have further questions, don't hesitate to reach our our [support](https://www.mailjet.com/support/ticket).

**Comment by joliejuke-orga** [comment]
Ok thanks, that's too bad, it could be great to have a full list of API routes and responses.
I also didn't find open source project that reference API mocks :s

**Comment by Zhivko-Mailjet** [comment]
Hi @joliejuke-orga,

We do not currently have all possible API routes and responses publicly available. We are continuously trying to improve and we will take your suggestion into consideration.

Meanwhile, you can take a look at how we test the wrapper in the [test directory](https://github.com/mailjet/mailjet-apiv3-nodejs/tree/master/test) and use a similar approach. I hope it will help you.

**Comment by gianpaj** [comment]
I believe if this library would use something like `axios`, for example, then we could mock the HTTP responses with https://github.com/ctimmerm/axios-mock-adapter

**Comment by gianpaj** [comment]
since this library uses `superagent` to send the HTTP requests it looks like it's already possible with https://github.com/M6Web/superagent-mock

**Comment by gianpaj** [comment]
Starting from this example: https://gist.github.com/ctrlplusb/190e426a01f1b9dc1140d7b9273175b8

Try something like this with `jest`:

`order.test.js`
```js
import superagent from 'superagent';
import mockSuperagent from 'superagent-mock'

describe('## Order APIs', () => {

  let superagentMock;
  let mailJetParams;

  const mailjetServerEndPoint = `https://api.mailjet.com/v3`;

  beforeAll(() => {
    superagentMock = mockSuperagent(superagent, [
      {
        pattern: `${mailjetServerEndPoint}`,
        fixtures: (match, params) => {
          mailJetParams = params;
          return {};
        },
        post: (match, data) => ({ body: data }),
      },
    ]);
  });

  afterAll(() => {
    superagentMock.unset();
  });


  describe('# Web Payments', () => {
    test('a seller confirms the order from the web', async done => {
      // an API request to your node.js server which will later trigger an email

      expect(mailJetParams.Messages[0].Subject).toBe('Somebody bought an item from you!');
      expect(mailJetParams.Messages[0].To[0].Email).toBe('seller@example.com');
    });
  });
});
```
