### ISSUE TITLE
The requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by Zerkley** [mailjet/mailjet-apiv3-nodejs#274]
Hello, I get this error:

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/node-mailjet.js?v=38aae28a' does not provide an export named 'default' (at useMail.tsx:1:1)`

when trying to import the dependency. It is the same error when I import like:

`import { Client } from 'node-mailjet';`

or

`import Mailjet from 'node-mailjet';`

I'm using it in a React web, using Typescript.

**Comment by dandv** [comment]
I get this with ts-node, no React or anything:

```
import { Client } from 'node-mailjet';
         ^^^^^^
SyntaxError: Named export 'Client' not found. The requested module 'node-mailjet' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by dandv** [comment]
@Zerkley ??

**Comment by andrew-goldie** [comment]
For anyone finding this issue and seeing it mysteriously closed without a resolution comment...

Try

```
import * as mailjet from "node-mailjet";
```

Then use that namespace like

```
const client = new mailjet.Client({ apiKey, apiSecret});
 ```
