### ISSUE TITLE
getting Wrong API version error

### ISSUE THREAD

**Issue by kaore** [mailjet/mailjet-apiv3-nodejs#3]
I'm trying to add a contact and I keep getting a 400 error response:

    var apiKey = process.env.MJ_APIKEY_PUBLIC,
    apiSecret = process.env.MJ_APIKEY_PRIVATE,
    mailjet = require( 'node-mailjet' ),
    mj = mailjet.connect( apiKey, apiSecret );

    mj.post( 'contact' )
    .request( { Email: 'some.random@email.com' } )
    .on( 'success', ( response, body ) => {} )
    .on( 'error', ( err, response ) => {
      console.log( response.statusCode );     // 400
      console.log( response.statusMessage );  // Wrong API version
    } );

**Comment by GuillaumeBadi** [comment]
Hey @kaore !
Thanks for using Mailjet! :)

Your code works on my side actually. Have you got any other information about this ?

Best,
Guillaume

**Comment by arnaudbreton** [comment]
Hi @kaore,

I lead Developers Relations here at Mailjet and I'm working with @GuillaumeBadi. 

Your account is currently using our V1 platform, our original one, now only maintained but not under active development. A new platform, called V3, has now became our official one. In order for you to use the API v3, we need to migrate your account to this new platform. 
For that operation to complete, I'll need to learn more about what you're doing with the API v1 so we can help you. Please send me these information over email to api@mailjet.com.

Have a great day,
Arnaud.
