### ISSUE TITLE
Error: Cannot find module 'apiv3' 

### ISSUE THREAD

**Issue by harshalyeole-tudip** [mailjet/mailjet-apiv3-nodejs#36]
Hi
I'm getting this issue.

Can you please help?

**Comment by latanasov** [comment]
Hi @harshalyeole-tudip, please provide some code samples where you are possibly trying to declare apiv3 etc. and I might be able to help you.

**Comment by harshalyeole-tudip** [comment]
I'm trying to integrate MailJet with the NodeJS.

I'm using following code:
const mailjet = require ('node-mailjet')
    .connect('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');


function testEmail (text) {
    email = {};
    email.FromName = 'Opto';
    email.FromEmail = 'xyz@abc.com';
    email.Subject = 'Checklist Email';
    email.Recipients = [{Email: 'abc@xyz.com'}];
    email['Text-Part'] = text;

    mailjet.post('send').request(email, function (err, response, body) {
        if (err) {
            console.log('Error-----------------------------------', err);
        } else {
            console.log('response================================',response);
            console.log('body------------------------------------', body);
        }
    })
}

testEmail('Hello World!');

**Comment by latanasov** [comment]
Hi @harshalyeole-tudip, please take a look at your other ticket first .

**Comment by harshalyeole-tudip** [comment]
Also,
I have a test account.

This is working fine with TEST APIKEYS and Registered test email.

But doesn't work on a paid account and its TEST APIKEYS and Registered test email.
