### ISSUE TITLE
There is no err sent on 400 Bad Request, body is returned as null

### ISSUE THREAD

**Issue by safani** [mailjet/mailjet-apiv3-nodejs#4]
Upon receiving a 400 there is no indication that there is an error.  body is null.

**Comment by GuillaumeBadi** [comment]
Hey @safani !

Thanks for using Mailjet! 
Can you paste you code so I can reproduce the error ?

Best,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hey @safani !

Did you manage to make it work ?
