### ISSUE TITLE
Can't resolve 'tls' -- Error on Mailjet connection

### ISSUE THREAD

**Issue by aloysius-tim** [mailjet/mailjet-apiv3-nodejs#42]
Hello,
I get this error while trying to connect to mailjet throwgh the node-mailjet library
`Can't resolve 'tls'`
I also got `Can't resolve 'dns'`
Anyone know how to resolve this issue ? My internet is working fine...

Thanks

**Comment by latanasov** [comment]
Hi @aloysius-tim are you maybe trying to use the wrapper in-browser (via javascript) ? Note this library is intended to be used on Node. 
If not please share your code example, plus complete API response.

**Comment by aloysius-tim** [comment]
Hi @latanasov, thanks for your answer !
Yes indeed I'm using it in browser using webpack... Not the most secured way but I thought it could work for a proto...
Anyway achieving this in browser ? If I use the REST api straigh away, do you think it would work ?

**Comment by latanasov** [comment]
Hi @aloysius-tim you will get into trouble with [CORS](https://spring.io/understanding/CORS). Even if you manage to bypass this security  mechanism, the effort won't be worth it for a prototype. Let me know if I can assist you with something else.

**Comment by aloysius-tim** [comment]
Thanks a lot 👍

**Comment by aloysius-tim** [comment]
You mean I would have CORS issue using the REST Api from the browser ? Without going through the node library ?

**Comment by latanasov** [comment]
Hi @aloysius-tim  yes, that's what I mean. Gave it a few attempts myself and run into this issue.

**Comment by aloysius-tim** [comment]
Hi @latanasov, so the only way is to build a rest API or going through PHP ? I was hoping to keep this simple as it's a silly landing page.
Thanks :)
