### ISSUE TITLE
Issue when trying to send variables for template language v3.1

### ISSUE THREAD

**Issue by nemanjapetrovic** [mailjet/mailjet-apiv3-nodejs#43]
Hi guys,

I have an issue sending template variables with v3.1 API:

So here it is:
I have template stored on your website with button HTML like:

```
<center>
    <a href="{{ var:userVerificationLink:"www.google.com" }}" class="btn-verify">
       Verify Address
    </a>
</center>
```

And I am sending API (v3.1, nodejs, npm:"node-mailjet": "3.2.1") request like this one:
```
"Messages ": [{
	"From ": {
		"Email ": "example@example.com",
		"Name ": "Some name"
	},
	"To": [{
		"Email ": "second@second.com",
		"Name ": "Some second"
	}],
	"TemplateID ": 1,
	"Variables": {
		"userVerificationLink": "http://localhost:8080/verify"
	}
}]
```

And my button in received HTML doesn't have at all href link, is there something else to add to this API call or?

**Comment by eboisgon** [comment]
Hello Nemanjapetrovic, 

In your message, you seem to be missing the following 
`"TemplateLanguage": true,`
This will indicate to the API that you want the template language to be processed. 
By default the processing is turned off. 

You can check [here ](https://dev.mailjet.com/guides/?javascript#using-templating-language)for more information 

Hope it helps

**Comment by nemanjapetrovic** [comment]
@eboisgon 

Yap, that was the problem. Thank you!
