### ISSUE TITLE
Connect() optional object being ignored?

### ISSUE THREAD

**Issue by maganap** [mailjet/mailjet-apiv3-nodejs#46]
I'm calling the connect method as in the README example:
```
// The third argument (the object) is not mandatory. Each configuration key is also optional
const mailjet = require ('node-mailjet')
    .connect(apiKey, apiSecret, {
        version: 'v3.1', // default is '/v3'
        perform_api_call: true // used for tests. default is true
      })
```

But the reply I get when sending the email has this structure:
```
{
  "Messages": [
    {
      "Status": "success", ...
      "To": [
        {
          "Email": "...",
          "MessageUUID": "0788ef45-716e-4d87-b735-04d134a59193",
          "MessageID": "70368744204343220",
          "MessageHref": "https://api.mailjet.com/v3/REST/message/70368744204343220"
        }
      ] ...
  ]
}
```

`MessageHref` shows a reference to API v3, instead of v3.1.

Also, if I set `perform_api_call: false` in the connect method (as the example from README), the email is still being delivered.
The API v3.1 reference mentions a different variable though:
https://dev.mailjet.com/guides/?javascript#sandbox-mode
But setting `SandboxMode: true` has the same effect: none. The email is still being delivered.

Am I doing something wrong? Or is it that the whole optional object is being ignored?
Thanks

**Comment by radmen** [comment]
@maganap you're doing everything fine. It's a bug in the SDK (https://github.com/mailjet/mailjet-apiv3-nodejs/issues/47)

There's a quick workaround for this:

```js
const mailjet = require ('node-mailjet')
    .connect(apiKey, apiSecret, { version: 'v3.1' })

mailjet.config.perform_api_call = false
```

**Comment by latanasov** [comment]
@maganap  the MessageHref will always be pointing to the /v3/REST/message, as this is the correct v(ersion) for this Resource. Only the Send API has both v3 and v3.1.

**Comment by maganap** [comment]
@latanasov I was just about to ask that again  :-)
So, it is taking the v3.1 option. Thank you for confirming v3 is actually what is expected as an answer from the api call.
