### ISSUE TITLE
Unable to set FALSE values for MailjetClient config

### ISSUE THREAD

**Issue by radmen** [mailjet/mailjet-apiv3-nodejs#47]
I wanted to set `perform_api_call` config variable for client:

```js
require('node-mailjet').connect(apiKey, apiSecret, {
    perform_api_call: false
})
```

This variable is omitted in `setConfig()` which results with sending API requests.

Bug is located here: 

https://github.com/mailjet/mailjet-apiv3-nodejs/blob/6840abd4ad8a8796aefb04f0cbaccc41a9344102/mailjet-client.js#L116-L119

`setConfig()` method will set values **only** when they're truthy.

**Comment by mskochev** [comment]
Resolved in v3.3.1
