### ISSUE TITLE
Weird handling of perform_api_call option

### ISSUE THREAD

**Issue by radmen** [mailjet/mailjet-apiv3-nodejs#48]
`perform_api_call` should prevent from sending API requests.

`httpRequest()` handles this in a rather weird way, which is probably a bug:

https://github.com/mailjet/mailjet-apiv3-nodejs/blob/6840abd4ad8a8796aefb04f0cbaccc41a9344102/mailjet-client.js#L193-L195

**Comment by mskochev** [comment]
Resolved in v3.3.1
