### ISSUE TITLE
Request: decrease number of dependecies

### ISSUE THREAD

**Issue by vladaman** [mailjet/mailjet-apiv3-nodejs#53]
Current dependency tree - difficult to keep track of what's safe and what's not. Currently 6.8MB.
```
├─┬ node-mailjet@3.2.1
│ ├─┬ json-bigint@0.2.3
│ │ └── bignumber.js@4.1.0
│ ├── qs@6.5.1
│ ├─┬ superagent@3.8.2
│ │ ├── component-emitter@1.2.1
│ │ ├── cookiejar@2.1.1
│ │ ├─┬ form-data@2.3.2
│ │ │ └── asynckit@0.4.0
│ │ ├── formidable@1.2.1
│ │ ├── methods@1.1.2
│ │ └── mime@1.6.0
│ └─┬ superagent-proxy@1.0.3
│   └─┬ proxy-agent@2.2.0
│     ├─┬ agent-base@4.2.0
│     │ └─┬ es6-promisify@5.0.0
│     │   └── es6-promise@4.2.4
│     ├── debug@2.6.9
│     ├─┬ http-proxy-agent@1.0.0
│     │ ├─┬ agent-base@2.1.1
│     │ │ └── semver@5.0.3
│     │ └── debug@2.6.9
│     ├─┬ https-proxy-agent@1.0.0
│     │ ├─┬ agent-base@2.1.1
│     │ │ └── semver@5.0.3
│     │ └── debug@2.6.9
│     ├── lru-cache@2.7.3
│     ├─┬ pac-proxy-agent@2.0.0
│     │ ├─┬ agent-base@2.1.1
│     │ │ └── semver@5.0.3
│     │ ├── debug@2.6.9
│     │ ├─┬ get-uri@2.0.1
│     │ │ ├── data-uri-to-buffer@1.2.0
│     │ │ ├── debug@2.6.9
│     │ │ ├── file-uri-to-path@1.0.0
│     │ │ └─┬ ftp@0.3.10
│     │ │   ├─┬ readable-stream@1.1.14
│     │ │   │ ├── isarray@0.0.1
│     │ │   │ └── string_decoder@0.10.31
│     │ │   └── xregexp@2.0.0
│     │ ├─┬ pac-resolver@3.0.0
│     │ │ ├─┬ degenerator@1.0.4
│     │ │ │ ├── ast-types@0.11.3
│     │ │ │ ├─┬ escodegen@1.9.1
│     │ │ │ │ ├── estraverse@4.2.0
│     │ │ │ │ ├── esutils@2.0.2
│     │ │ │ │ ├─┬ optionator@0.8.2
│     │ │ │ │ │ ├── deep-is@0.1.3
│     │ │ │ │ │ ├── fast-levenshtein@2.0.6
│     │ │ │ │ │ ├── levn@0.3.0
│     │ │ │ │ │ ├── prelude-ls@1.1.2
│     │ │ │ │ │ ├── type-check@0.3.2
│     │ │ │ │ │ └── wordwrap@1.0.0
│     │ │ │ │ └── source-map@0.6.1
│     │ │ │ └── esprima@3.1.3
│     │ │ ├── ip@1.1.5
│     │ │ ├── netmask@1.0.6
│     │ │ └── thunkify@2.1.2
│     │ └─┬ raw-body@2.3.2
│     │   ├── bytes@3.0.0
│     │   ├─┬ http-errors@1.6.2
│     │   │ ├── depd@1.1.1
│     │   │ ├── setprototypeof@1.0.3
│     │   │ └── statuses@1.5.0
│     │   ├── iconv-lite@0.4.19
│     │   └── unpipe@1.0.0
│     └─┬ socks-proxy-agent@3.0.1
│       └─┬ socks@1.1.10
│         └── smart-buffer@1.1.15
```

**Comment by pthm** [comment]
The worst offender here is `superagent-proxy` which is required for the http proxy functionality.

Superagent as a dependency could easily be removed, but replacing the `proxy-agent` dependency would require some work.

I would suggest a breaking change of removing the proxy entirely and allowing users to specify an agent to override the one used by the library. This would reduce the size of the module considerably and users who need proxy functionality could install the `proxy-agent` module into their own projects.

Happy to have a go at making these changes if they are considered worthwhile.

**Comment by todorDim** [comment]
Hello @vladaman,

This has been passed to our developers and we're looking to reduce the amount of dependencies in the next version.

Regards,
T.

**Comment by ricky11** [comment]
Any  update on this https://bundlephobia.com/package/node-mailjet@3.3.4 shows that mailjet is still using bluebird and superagent and many outdated packages.

**Comment by scroll17** [comment]
Hey @vladaman @pthm @ricky11 

Dependency `bluebird` was removed in the current version `3.1.12`.

You can use `npm audit` for follow all vulnerable dependencies in your project.

What about `superagent` and `superagent-proxy` this libraries at the current version of mailjet-apiv3-nodejs have last versions and they not marked as vulnerable dependencies. And in general the last version of [mailjet-apiv3-nodejs](https://github.com/mailjet/mailjet-apiv3-nodejs) haven't any vulnerabilities and this library already has good support and will continue to develop more fast.

In a future major release, most likely `superagent` and `superagent-proxy` will be removed and replaced with something more modern and more freedom for users as suggested by @pthm
