### ISSUE TITLE
HTML-Parts - How in the world do i send HTML?

### ISSUE THREAD

**Issue by ksummersill** [mailjet/mailjet-apiv3-nodejs#56]
I have read multiple API documentation and am utilizing the Text-Parts; however how do i send HTML?

**Comment by ngarnier** [comment]
You just need to pass your HTML as the `HTMLPart`, example here with the Send API v3.1: https://dev.mailjet.com/guides/?javascript#sending-a-basic-email.

**Comment by ksummersill** [comment]
So am able to send text utilizing the Text-Part example within this hub; i didn't know if you had a HTML-Part element that i could use as well.
