### ISSUE TITLE
connect function fails silently when no valid credentials are given

### ISSUE THREAD

**Issue by theobat** [mailjet/mailjet-apiv3-nodejs#58]

**Comment by iyobo** [comment]
Maljet's API lacks basic error handling in general. 
Good luck using them. See https://github.com/mailjet/mailjet-apiv3-nodejs/issues/57

**Comment by todorDim** [comment]
Hi @theobat ,

We're working on another version of the wrapper. Indeed the error handling is something we're willing to improve.

Regards,
T.
