### ISSUE TITLE
File Attachment

### ISSUE THREAD

**Issue by ratnam99** [mailjet/mailjet-apiv3-nodejs#63]
Hi,
Is there a way to attach a file to mail. I have been trying to follow the docs but was not able to do so.

My use case is, I have a file named- `xyz.pdf` on disk and I wish to attach this file in the mail and then send it.

```
const request = mailjet.post("send").request({
    "FromEmail":"dummy-email@gmail.com",
    "FromName":"Dummy",
    "Subject":"Your email flight plan!",
    "Text-part":"Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    "Html-part":"<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with 
     you!",
    "To": "dummy2-email@gmail.com",
    "Attachments": [{
       "Filename": 'xyz.pdf',
    }]
});
```

**Comment by adamyanliev** [comment]
Hey @ratnam99 , 

It is possible to attach a file via the Send API, but you need to specify the file name, content type via a MIME type, and the content as encoded in Base64. So in your example you are missing two properties in `Attachments` - `ContentType` and `Base64Content`.

For PDF the MIME type is `application/pdf`. You can see the official list of MIME types [here](https://www.iana.org/assignments/media-types/media-types.xhtml).

For the content you can find a Base64 encoder online - e.g. [here](https://www.freeformatter.com/base64-encoder.html). Once you encode the file, use the resulted string as the value of `Base64Content`.

Finally, make sure that you are using the correct Send API version your Mailjet account is on. The example you gave is for SendAPI v3 - if you are on SendAPI v3.1, there are some differences in the syntax and properties used. See [here](https://dev.mailjet.com/guides/?javascript#sending-with-attached-files) for more info.
