### ISSUE TITLE
Typings for Typescript

### ISSUE THREAD

**Issue by Kamshak** [mailjet/mailjet-apiv3-nodejs#66]
Hi, are there any typings available for use with typescript? If not please consider this a feature request :) Would be really great to have!

**Comment by todorDim** [comment]
Hello @Kamshak,

Feature request taken into account :)

Regards,
T.

**Comment by Nikola-Andreev** [comment]
Hi.
The types are are published in npm and ready for use now. Here is the npm page:
https://www.npmjs.com/package/@types/node-mailjet

Feel free to request changes if there is something missing or you just suggest an improvement.

The main repository is here:
https://github.com/DefinitelyTyped/DefinitelyTyped

And here is the file with our types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-mailjet/index.d.ts

Regards.
