### ISSUE TITLE
Total number of recipients exceeded. Max allowed - 50

### ISSUE THREAD

**Issue by cerealexx** [mailjet/mailjet-apiv3-nodejs#67]
Our backend is trying to send about 200 emails through the Mailjet API following the instructions in: https://dev.mailjet.com/guides/?javascript#sending-in-bulk 

We get a limit error of 50 recipients though. Is there a way to rise this limit? Should our system send several requests for every 50 recipients instead? If so, is there a time we need to wait from request to request?

Thanks

**Comment by cerealexx** [comment]
Support already answered me. Thx!

**Comment by ryanprater** [comment]
@cerealexx it would help if you posted what they responded

**Comment by adamyanliev** [comment]
hey @ryanprater ,

The Send API v3.1 is limited to sending 50 messages in a single request. This can mean a single message object with 50 recipients, 50 different messages with one recipient each, or anything in-between. If you need to send a higher number, you should set up additional calls. 

The Send API v3.1 can process 500 calls every 10 seconds, so unless your sending volume is extremely high, you should be fine setting up the the API calls without any waiting periods.

Regards,
Atanas

**Comment by KOfferman** [comment]
@cerealexx can you share the answer?
