### ISSUE TITLE
Offset filter not working

### ISSUE THREAD

**Issue by jorgeartigas** [mailjet/mailjet-apiv3-nodejs#68]
Hello,
I'm trying to get all the emails in a specific contact list that has more than 1000 contacts (max limit per request) 
So I'm doing a second call with the Offset filter to retrieve the next contacts starting form the filter... and so on
Am I'm doing something wrong?

This is my code, the contact list has ~1270 contacts so this code should return ~270 contacts but instead is returning the same first 1000 results as if Offset filter wasn't presen

```
return nodeMailjet
            .get('contact')
            .request(
                {
                    "ContactsList": $id,
                    // 0 for max results (1000)
                    "Limit": 0,
                    "Offset": 1001
                }
            )
            .then((result) => {
                console.log(result.body.Data.length);
                console.log(result.body.Data)
            })
            .catch((err) => {
                console.log(err)
                return err;
            });
```

**Comment by ngarnier** [comment]
hey @jorgeartigas, this is because you set the limit to 0. Set the offset to your Limit + 1 and it will work. So: 
```
                    "Limit": 1000,
                    "Offset": 1001
```

Let us know if the issue persists.

**Comment by jorgeartigas** [comment]
Oh!! Thank's now I'm able to get the exact number of emails

But what about if the contact list has 2500 contacts?
The limit always has to be equal to the Offset, even if the max results per request is 1000?

Example first call I set:
```
"Limit": 0,
"Offset": 0
```
2nd:
```
"Limit": 1000,
"Offset": 1000
```
and the 3rd should be: ?
```
"Limit": 2000,
"Offset": 2000
```

**Comment by ngarnier** [comment]
No:

- The limit is 1,000 maximum, so it should always be set to 1,000 (or a lower value if you don't want to retrieve them by groups of 1,000)
- The offset is the element at which you want to start the listing, so this is what you want to update at each call

This gives:
1st call:
```
"Limit": 1000,
"Offset": 0
```
2nd:
```
"Limit": 1000,
"Offset": 1000
```
3rd:
```
"Limit":1000,
"Offset": 2000
```

Of course you can also set the Offset programatically based on the limit.

**Comment by jorgeartigas** [comment]
Perfect, thanks!
