### ISSUE TITLE
EventEmitter ≠ Promise

### ISSUE THREAD

**Issue by p-j** [mailjet/mailjet-apiv3-nodejs#7]
Hi there,

I'm a bit confused with the documentation/readme :

Why would you say [Make the same request with a **promise**](https://github.com/mailjet/mailjet-apiv3-nodejs#make-the-same-request-with-a-promise) or call it a [promise](https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/mailjet-client.js#L142) when it's clearly [not a promise](https://promisesaplus.com/) ?

I would suggest to either go with promise and use something like [petkaantonov/bluebird](https://github.com/petkaantonov/bluebird) to return a `thenable` or stay with the EventEmitter pattern and stop advertising it as something it isn't.

I've made the required change for a [proper Promise](https://github.com/vizeat/mailjet-apiv3-nodejs/commit/b62fcb6128804c75b5238f8bf99bd31db00c388f?w=1) implementation (both code & test)
along with [consistency fix](https://github.com/mailjet/mailjet-apiv3-nodejs/compare/master...vizeat:feat/promise?expand=1) (code style & line endings). 
I've used [standardjs](http://standardjs.com/) as code style because it is what I use, but if you'd rather keep semicolons you can checkout [semistandard](https://github.com/Flet/semistandard) and LF line endings instead of mixed CR & LF.

If you like it I can make a [pull request](https://github.com/mailjet/mailjet-apiv3-nodejs/compare/master...vizeat:feat/promise?expand=1), I've already bumped the major version in the `package.json` as moving away from EventEmitter is a breaking change.

Either way, thanks for putting together this package as a starting point for using Mailjet API :-)

**Comment by GuillaumeBadi** [comment]
Hey ! 

Yes right, At the time, there were no stable implementation of the Promise API, but yes you are right, I think you can open a pull request with a major version update in the package.json, it will be merged!

Thanks,
Guillaume

**Comment by p-j** [comment]
Just did :-)
Thanks for the quick reply !
