### ISSUE TITLE
How to get contact ID from its email ?

### ISSUE THREAD

**Issue by BenjaminDish** [mailjet/mailjet-apiv3-nodejs#74]
Hello,

I'm using the api with the Java SDK and I'm migrating my backend to NodeJS (using the Node SDK).

I can't find out how to get a contactId from its email.

Here is my Java working code : 
```
public Integer getContactId(String email){
    	if(email != null){    			
			MailjetRequest request = new MailjetRequest(Contact.resource, email);    						
			try {
				JSONArray response = get(request);
				if(response.length() > 0){
					JSONObject o = response.getJSONObject(0);
					return (Integer)o.get("ID");
				}
				else{
					return null;
				}			
			} catch (Exception e) {
				e.printStackTrace();
				Logger.error("Error while calling getContactId");
				return null;
			}				
		}
		else{
			return null;
		}  		
    }
```

and here is my Node non-working code: 
```
public static async getContactId(email: string): Promise<number> {
        if (!_.isNil(email) && email !== "") {
            return MailjetApiService.client()
                .get('contact')
                .request({
                    "Email": email,
                }).then((result) => {  
                    console.log(result.body.Data);                 
                    if (Array.isArray(result.body.Data) && result.body.Data.length > 0) {
                        return result.body.Data[0]["ContactID"];
                    }            
                }).catch((e) => {
                    console.log(e);
                    logger.error(e, "Error while calling getContactId");
                    return null;
                });
        }
        else {
            return null;
        }
    }
```

Indeed, with Node, the console.log of the output prints the list of the 10 first contacts of my Mailjet account. So the "Email" field is not filtering results.

What did I miss ?
Thank you

**Comment by mskochev** [comment]
Hello Benjamin,

This code should give you the contact ID: 
<pre>const request = mailjet
   .get("contact")
   .id($EMAIL_ADDRESS_OR_CONTACT_ID)
   .request()
</pre>

Also you should use `result.body.Data[0]['ID']` instead of `result.body.Data[0]["ContactID"]` to get the contact ID.

Some further reading: https://dev.mailjet.com/guides/?javascript#unique-key-filters

**Comment by BenjaminDish** [comment]
Thank you @mskochev ! 
It solved my problem.

I close the issue !
