### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by webmobiles** [mailjet/mailjet-apiv3-nodejs#79]
what does mean this error when i try to send this email:

"self signed certificate in certificate chain"

this problem i'm not getting from my mac, but yes from a server built with docker.

**Comment by Thoradin89** [comment]
Hello @webmobiles 

Can you provide us some information about what you're trying to do ?

Regards,
T.

**Comment by webmobiles** [comment]
it's ok , it needed config the proxy server with mailjet
