### ISSUE TITLE
React CRA errors 401 Unauthorized

### ISSUE THREAD

**Issue by RobyRemzy** [mailjet/mailjet-apiv3-nodejs#81]
Hi, i did setup an account and Authenticate my domains (SPF / DKIM) and my Sender is on the same domain that i setup mailjet with.
I was wondering if the api is fine with React create react app. I setup my code like this:
note the set to FALSE here ` perform_api_call: false // used for tests. default is true`

```js
import * as mailjet from "node-mailjet";
import React, { Component } from "react";
import "./App.css";

const MJ_APIKEY_PUBLIC = "1234567890";
const MJ_APIKEY_PRIVATE = "1234567890";
const Sender = "my@mail.com";
const Receiver = "my2@mail.com";

mailjet
  .connect(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE, {
    url: "api.mailjet.com", // default is the API url
    version: "v3.1", // default is '/v3'
    perform_api_call: false // used for tests. default is true
  })
  .post("send", {
    url: "api.mailjet.com",
    version: "v3.1",
    perform_api_call: false
  })
  .request({
    Messages: [
      {
        From: {
          Email: Sender,
          Name: "Mailjet Pilot"
        },
        To: [
          {
            Email: Receiver,
            Name: "passenger 1"
          }
        ],
        Subject: "Your email flight plan!",
        TextPart:
          "Dear passenger 1, welcome to Mailjet! May the delivery force be with you!",
        HTMLPart:
          "<h3>Dear passenger 1, welcome to Mailjet!</h3><br />May the delivery force be with you!"
      }
    ]
  })

  .then(
    response => {
      console.log(response.body);
    },
    err => {
      console.log(err.body);
    }
  );

class App extends Component {
  render() {
    return <div className="App">hello!</div>;
  }
}

export default App;
```

i do a `yarn install` and `yarn start` open my app on `http://localhost:3000/` and the console log is ok i can see my response...

But if i set to TRUE here ` perform_api_call: true // used for tests. default is true`

the console.log is mad at me with :

- Refused to set unsafe header "user-agent"
- OPTIONS https://api.mailjet.com/v3.1/send 401 (Unauthorized)
- Access to XMLHttpRequest at 'https://api.mailjet.com/v3.1/send' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I did try the first curl request on the doc and it's working. I wonder what i did wrong here ? Can i do something like this, like in my app trigger the api to send an email? do i need more config to counter the cors situation?

thanks!

**Comment by Thoradin89** [comment]
Hello @RobyRemzy 

We'll take a closer look at it and we'll get back to you.

Regards,
T.
