### ISSUE TITLE
Can't send email with template

### ISSUE THREAD

**Issue by gyurobenjamin** [mailjet/mailjet-apiv3-nodejs#82]
API response is 200, everything seems fine.

```javascript
sender.request({
    Messages: [{
      From: {
        Name: '',
        Email: 'my@email',
      },
      To: [{
        Email: to,
      }],
      TemplateID: template,
      TemplateLanguage: true,
      TemplateErrorReporting: {
        Email: 'my@email',
        Name: '',
      },
      Subject: "#",
      // TemplateErrorDeliver: true,
      Variables: {
        name: '',
      },
    }],
  }); 
```

But I don't receive the email, if I turn on the ```TemplateErrorDeliver: true``` then I receive the email, but with the variable names and brackets just like this:

```
Hi {{ date }},
....
```

Also I receive no error email, doesn't matter if I set the ```TemplateErrorReporting``` or not.

There is no way to debug this issue on my side...

**Comment by gyurobenjamin** [comment]
Ah... the issue was a space. So I couldn't use ```{{ var:date:"" }}``` But I can this way: ```{{var:date:""}}```

**Comment by Thoradin89** [comment]
Hello @gyurobenjamin 

Since you discovered the fix for your issue, I will close it. In case you need anything else, feel free to reopen it.

Regards,
T.
