### ISSUE TITLE
Empty messages

### ISSUE THREAD

**Issue by ekkis** [mailjet/mailjet-apiv3-nodejs#84]
I have some code that works in my test environment but fails in production, where production is the Now serverless platform

what's odd is the message gets sent in production but with an empty body.  I'm setting both TextPart and HTMLPart and neither arrives.  here's the code:
```js
{
  Messages: [{
    "From": {"Name":"A bot","Email":"x@x.com"},
    "To":[{"Email":"x@x.com"}],
    "Subject":"testing",
    "HTMLPart":"<!doctype html>\n<html>...</html>\n\n",
    "TextPart":"Greetings..."
  }]
}
```
and for the record, I call it like this:
```js
try {
    var ret = await req.post("send", {'version': 'v3.1'}).request(m);
    if (ret.body.Messages[0].Status == 'success') console.log('all good')
}
catch (e) {
    console.log(e)
}
```
and I get "all good"... any suggestion as to how I might troubleshoot or something to change about the code?

**one important thing: Now is running on NodeJs v8**

**Comment by ekkis** [comment]
ok.  I downgraded my workstation to v8 and the package works fine.  so it's some other kind of problem

**Comment by abambova** [comment]
We will close the issue in this case. Please feel free to open a new one if needed.
