### ISSUE TITLE
v3 Compatibility 

### ISSUE THREAD

**Issue by towfiqi** [mailjet/mailjet-apiv3-nodejs#86]
Hi,

Do we need add the `MessageUUID` to our calls for the upcoming version 3? or are you guys going to update the package and we don't have to make any changes?
https://dev.mailjet.com/guides/#send-api-v3

Let me know

**Comment by LSPThrillworks** [comment]
Also interested in this

**Comment by andrii-yelis** [comment]
The library supports v3. I'm closing the issue. In case you have some problems with it please open a new one.
