### ISSUE TITLE
Question : delete a contact

### ISSUE THREAD

**Issue by MarcelPitch** [mailjet/mailjet-apiv3-nodejs#9]
Hi,

I have to sync a contacts list from our db to a **MailJet** contacts list.

*In a specific case*, I have to **delete** a contact from a contacts list.

On your documentation, I've seen the way to do that is to use the `listrecipient` entity.

But I didn't find what a way to get the `listrecipient` ID from a `contact` entity.

Or maybe we can proceed directly from `contact` entity ?

Thanks for your reply and have a nice day.

**Comment by GuillaumeBadi** [comment]
Hey @MarcelPitch !

Can you paste your code here so I can give you a solution ?

**Comment by GuillaumeBadi** [comment]
Any news here @MarcelPitch
