### ISSUE TITLE
async sample for Azure Function Apps

### ISSUE THREAD

**Issue by tiwari-abhishek** [mailjet/mailjet-apiv3-nodejs#91]
I am looking for an async sample for Azure Function Apps. The mails are sent but the function call just hangs in Azure Function and the function runs for roughly 10 minutes before failing. This becomes very expensive as the function app to send email should barely run for ~100ms or so.

Any suggestions?

**Comment by ydrews** [comment]
Hello @tiwari-abhishek 

Could you please provide your Function code?

**Comment by andrii-yelis** [comment]
I tested it with azure function and it works well. Maybe you had an issue in your code.
Closing the issue and if you have something else please reopen it or create a new one. Thanks!
