### ISSUE TITLE
Subject is Required Property in SendParamsMessage

### ISSUE THREAD

**Issue by FlorianPfisterer** [mailjet/mailjet-apiv3-nodejs#93]
When using a dynamic template (Mailjet Passport, `TemplateLanguage: true`) in the Send API (v3.1), the subject line of an email can be set up in the template itself, and thus does not need to be included in the parameters.

I'm referring to the corresponding [TypeScript type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-mailjet/index.d.ts#L102). 

If you pass `Subject: ''`, it will take the subject from the template, but variables in the subject (e.g. `{{var:username:""}}`) are not replaced (in the email body, they are). 

The way I fixed it is to just go around the type-safety in TypeScript and pass an object without the `Subject` property, but this is obviously not the way it should be.

**Comment by acestudiooleg** [comment]
@FlorianPfisterer  you can use an empty string if you need a subject from the template, but I agree, this param should be optional.
