### ISSUE TITLE
Incorrect docs: contact_managecontactslists error "Method not allowed"

### ISSUE THREAD

**Issue by dundas** [mailjet/mailjet-apiv3-nodejs#94]
These docs are infuriating. I am getting an error with this call. 

const mailjet = require ('node-mailjet')
	.connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)
const request = mailjet
	.post("contact_managecontactslists")
	.id(Contact_ID)
	.request({
    "ContactsLists": [{
			"ListID": 987654321,
			"Action": "addnoforce"
		}]
	})
request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})

**Comment by adamyanliev** [comment]
hi @dundas ,

Apologies, the code sample in the readme is incorrect. This is the correct syntax:

```
...
const request = mailjet
	.post("contact")
	.id($contact_ID)
	.action("managecontactslists")
	.request({
...
```

I've corrected the sample now. Thanks for letting us know about this and please don't hesitate to post again if you find other issues or have suggestions on how to improve the docs.

Regards,
Atanas
