### ISSUE TITLE
node compatibility

### ISSUE THREAD

**Issue by sakulstra** [mailjet/mailjet-apiv3-nodejs#95]
Hello,
we're currently considering mailjet to replace mailchimp+mailgun in our application - partly due to an "official node integration".

Looking into this official integration raises some questions:
- is this library compatible with modern node projects?

Both [travis ci](https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/.travis.yml#L6) and [readme](https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/README.md#compatibility) state that the latest supported node version is `6.x` which has reached [end-of-life](https://github.com/nodejs/Release#end-of-life-releases) quite some time ago.
Are there any plans to support node 10 or 12 in the near future and perhaps even drop bluebird as all non-EOL node versions have a native promise support?

**Comment by choopage** [comment]
I tested this library. It works with Node version 10.
Indeed node version 6 are deprecated. And version 8 is going to be deprecated too.
So I upgraded to Node version 10 using https://github.com/mailjet/mailjet-apiv3-nodejs 

In brief, this package works with Node version 10.

**Comment by danactive** [comment]
"A list of official programming language libraries created and maintained by the Mailjet team." Node.js client is clearly not maintained. I'm curious about vulnerabilities with the stale dependencies
