### ISSUE TITLE
/contactslist ManageManyContacts "Contacts.Name" not used

### ISSUE THREAD

**Issue by ddett** [mailjet/mailjet-apiv3-nodejs#99]
I followed an example from the Mailjet docs to add an email and an associated name to a contacts list. The email was added fine, but the name just disappeared. 

Here's the example from the Mailjet docs:

`"Contacts":[
        {
          "Email":"passenger@mailjet.com",
          "IsExcludedFromCampaigns":"false",
          "Name":"Passenger 1",
          "Properties":"object"
        }
      ]`

https://dev.mailjet.com/email/guides/contact-management/#bulk-contact-management

The solution was to specify the name as a property like this:

`"Contacts":[
        {
          "Email":"passenger@mailjet.com",
          "Properties": { name: "Passenger 1" }
        }
      ]`

After that change the name finally appears in the contact list just as expected.
Took me a while to figure that out. 

I guess the docs should be adjusted?

**Comment by adamyanliev** [comment]
Hi @ddett ,

The purpose of the `Name` property for a contact is mainly for you to more easily recognize it when retrieving your contacts. If you do a `GET` on `/contact/passenger@mailjet.com`, you will see the value you have selected for `Name` in the response. This "contact name" will not be displayed in the app.

On the other hand, what you did with your second call is add contact data for that contact. Anything you have set up as contact data can later be used for email personalization, as well as to target specific segments of your contact lists. 

I hope this clarifies things, and thanks for the feedback, I'll take a look at how we can better explain it in the documentation.

Regards,
Atanas
